### ISSUE TITLE
git master not deployed?

### ISSUE THREAD

**Issue by Br3nda** [openfarmcc/OpenFarm#1057]
#1052 not deployed

running from git master, and requesting:
http://localhost:3000/api/v1/crops.json?page=1
I get lots of results

but when i request the same from production
https://openfarm.cc/api/v1/crops.json?page=1
i get an empty dataset

was the git master from Thu Aug 29 deployed to production?

**Comment by RickCarlino** [comment]
I think we're good now @Br3nda . That last deploy may have failed for unknown reasons :man_shrugging:
