### ISSUE TITLE
broken images

### ISSUE THREAD

**Issue by Br3nda** [openfarmcc/OpenFarm#1065]
any idea why all the photos for tomatoes are broken
https://openfarm.cc/en/crops/tomato
Looks like an AWS permission - i get 403 errors.
https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5d6063d2fd619c00041d4371.jpg?1566598095

**Comment by Br3nda** [comment]
I've uploaded photos of feijoa (there were none). They save into s3, but they have some permission error and

https://openfarm.cc/en/crops/feijoa

Saved image : https://s3.amazonaws.com/openfarm-project/production/media/pictures/attachments/5d7f034b5186a00004e90299.jpg?1568605002

Returns a http 403

**Comment by roryaronson** [comment]
Thanks for the bump on this @Br3nda, I've asked @RickCarlino to take a look :)

**Comment by Br3nda** [comment]
@roryaronson this is still broken. Can i have heroku access to look further into this error?

**Comment by roryaronson** [comment]
@Br3nda yes, thank you for offering to help. Can you email me (rory@farmbot.io) with the email address you want to use to access Heroku with? I'll also need to add you to the AWS account I think. Rick is also looking back into this again today. We unfortunately got sidetracked the last month

**Comment by Br3nda** [comment]
I only uploaded one image  yet there are multiple broken images attached to the crop. Could be a offline or rake task that is running over and over.

**Comment by RickCarlino** [comment]
Possible root cause: https://github.com/dtan4/terraforming/issues/235

Still investigating :hourglass_flowing_sand:
