### ISSUE TITLE
Develop Terms and Conditions

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#113]
I'm going to find a similar site's terms and modify them for OpenFarm. They'll need to be checked over by a lawyer. If anyone knows someone who wants to do some pro-bono work, please send them my way at rory@openfarm.cc. I can also ask the Kickstarter pool (1,000+ people) in the next update.

**Comment by roryaronson** [comment]
Where are these located? I found our Privacy Policy (via the footer) but not these terms.

**Comment by simonv3** [comment]
Hmmm, yeah, the page is there, but it just has privacy policy stuff on it. Will fix.

**Comment by roryaronson** [comment]
Ok, a few things. This doesn't really mention anything about content being released to the public domain. It also mentions FarmBot as the legal entity, which we can now change to OpenFarm. Here are updated terms that I think bring us ready for launch. cc @simonv3

<h1>Terms of Service ("Terms")</h1>
<p>Last updated: January 14, 2015</p>

<p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the https://openfarm.cc website (the "Service") operated by OpenFarm Inc ("us", "we", or "our"), a California 501(c)3 non-profit.</p>

<p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.</p>

<p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>




<p><strong>Content</strong></p>

<p>Our Service allows you to create, post, link, store, share and otherwise make available certain information, text, data, graphics, photos, videos, or other material ("Content"). You are responsible for the Content that you post to the Service, including its legality, reliability, and appropriateness.</p>

<p>By posting Content to the Service, you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service under a <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0 Public Domain Dedication</a>. You are dedicating all Content you submit, post, or display to the public domain by waiving all of your rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. All others can copy, modify, distribute and perform the work, even for commercial purposes, all without asking for your permission. You agree that this license includes the right for us to make your Content available to other users of the Service, who may also use your Content subject to these Terms.</p>

<p>You represent and warrant that: (i) the Content is yours (you own it) or you have the right to use it and grant us the rights and license as provided in these Terms, and (ii) the posting of your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person.</p>

<p><strong>Accounts</strong></p>

<p>When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.</p>

<p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.</p>

<p>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>    

<p>You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trade mark that is subject to any rights of another person or entity other than you without appropriate authorization, or a name that is otherwise offensive, vulgar or obscene.</p>


<p><strong>Intellectual Property</strong></p>
<p>The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of OpenFarm Inc and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of OpenFarm Inc.</p>

<p><strong>Links To Other Web Sites</strong></p>

<p>Our Service may contain links to third-party web sites or services that are not owned or controlled by OpenFarm Inc.</p>

<p>OpenFarm Inc has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that OpenFarm Inc shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>

<p>We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.</p>

<p><strong>Termination</strong></p>

<p>We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

<p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

<p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.</p>
<p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

<p><strong>Indemnification</strong></p>

<p>You agree to defend, indemnify and hold harmless OpenFarm Inc and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password, or b) a breach of these Terms.</p>
<p>You agree to defend, indemnify and hold harmless OpenFarm Inc and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms, or c) Content posted on the Service.</p> 

<p><strong>Limitation Of Liability</strong></p>

<p>In no event shall OpenFarm Inc, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

<p><strong>Disclaimer</strong></p>

<p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.</p>

<p>OpenFarm Inc its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.</p>

<p><strong>Exclusions</strong></p>

<p>Some jurisdictions do not allow the exclusion of certain warranties or the exclusion or limitation of liability for consequential or incidental damages, so the limitations above may not apply to you.</p>

<p><strong>Governing Law</strong></p>

<p>These Terms shall be governed and construed in accordance with the laws of California, United States, without regard to its conflict of law provisions.</p>

<p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>

<p><strong>Changes</strong></p>

<p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>

<p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>

<p><strong>Contact Us</strong></p>

<p>If you have any questions about these Terms, please contact us at info@openfarm.cc.</p>
