### ISSUE TITLE
Support Do Not Track

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#137]
Need to support this for compliance and because our Privacy Policy says we do ;)

**Comment by simonv3** [comment]
Anyone have any thoughts on this?

**Comment by simonv3** [comment]
@RickCarlino @roryaronson 

So my understanding is that do not track is a header sent to us by the browser on which condition we should not track the user across sites. Since we're not tracking users across sites - and I don't see us doing so any time soon - is this a problem?

**Comment by RickCarlino** [comment]
@simonv3 My ultimate conclusion was that very, very few people are supporting `x-do-not-track`. I couldn't find any real world examples of people who had integrated it into Rails. That gem you posted looks promising, though.

**Comment by roryaronson** [comment]
From Wikipedia: "...requests that a web application disable either its tracking or cross-site user tracking (the ambiguity remains unresolved) of an individual user."

So we're covered on the cross site tracking because we don't do those shenanigans anyways. Though it would be a privacy nicety to allow users to 1) opt out of our analytics tracking via a user setting and 2) prevent Google analytics from working when we get a DNT request.

Though at the end of the day this standard isn't set yet and I don't think it would be the best use of our time to build something from scratch. If a drop in gem can do it quick, I'm all for it!

**Comment by warpling** [comment]
Do Like buttons constitute cross-site tracking?

**Comment by simonv3** [comment]
They do, but those like buttons are for Facebook, not for us, we're not
doing the tracking. If we had guide widgets (idea!) And we kept track of
where people viewed them, than that would be tracking I think.

It might not be that big of deal to check for the browser header to Do Not
Track and wrap our analytics in an if statement to catch that?

I'll look into that.
