### ISSUE TITLE
[BUG] Badge not rendering correctly in readme

### ISSUE THREAD

**Issue by darigovresearch** [openfarmcc/OpenFarm#1396]
There appears to be a badge not rendering correctly in the readme.

Happy to do a pull request if shown how to correct it

![image](https://user-images.githubusercontent.com/30328618/233781225-acbb0940-75c0-44ad-a78a-c4304d8ec873.png)

**Comment by davidomullan** [comment]
My guess is this project was built for the Rails Rumble competition in 2015. Seems like the site is no longer hosted. Recommend removal from README.md.
