### ISSUE TITLE
Digital Badges

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#164]
People love em! It builds a sense of pride for each user, provides glanceable info about each Guide or comment author's credibility, and we need to give them to our Kickstarter backers :)

Some ideas for different badges:
* Kickstarter Backer Badge
* Country flags for user's location
* Guide Author (1 Guide, 3 Guides, etc)
* Crop Editor (1 Crop, 3 Crops, etc)
* Forum Poster (1 Comment, 25 Comments, etc)
* OpenFarm Developer
* Account Age (1 year, 2 year, etc)

Anyone know of a good plug and play badge system or should we just roll them into User Profiles?

**Comment by simonv3** [comment]
This exists as of #533.

Edit this file to add badges:
https://github.com/openfarmcc/OpenFarm/blob/master/config/initializers/merit.rb

And here to add rules for said badges:
https://github.com/openfarmcc/OpenFarm/blob/master/app/models/merit/badge_rules.rb

next step is adding some sort of visual representation of the badge on the frontend.

@roryaronson I know this was planned on the guide next to the username, is that where we still want to focus that for now?

**Comment by roryaronson** [comment]
Awesome work Simon. I think displaying 3-5 badges next to usernames is the most logical spot in order to get the trust/confidence/legitimacy feeling that badges create. I suppose these 3-5 badges could be chosen by the user to be their 'featured' badges?

Then on a user's profile page, all of them could be displayed in a dedicated badges section.

**Comment by simonv3** [comment]
We could also do a hover over to show all badges.

**Comment by roryaronson** [comment]
I like that idea. I think every badge should also have a tooltip that says the badge's name and description of how it was achieved.

**Comment by roryaronson** [comment]
I'm going to close this one and work on some mockups for how we can display badges both next to usernames and on user profile pages
