### ISSUE TITLE
Adding new gardens

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#293]

**Comment by aukjan** [comment]
I tried to add a Garden (in Chrome), but going to the 'Gardens' page, showed nothing but a 'header' with 'Your Gardens'. Is this correct?

**Comment by simonv3** [comment]
Hey @aukjan, that could potentially be normal if you have registered with the site before gardens were a feature. At the moment (as you can see from it being an issue) you can't create gardens yet, but new sign ups will automatically get one created for them. 

Having said all of that! This is pretty not-acceptable, I'll see if I can do something about it in the next two hours.

@warpling it looks like some of the styling on guides broke the styling on the garden page.

**Comment by aukjan** [comment]
Yep, I registered a long while back ;), and just now visited again ... No biggie, but yep, it should be fixed... 

Thanks for the quick reply! (BTW, i noticed it because looking at a guide it does show the parts that match my Garden.)

**Comment by simonv3** [comment]
@aukjan just pushed some changes live that should address this. Have a look at https://openfarm.cc/users/gardens

**Comment by aukjan** [comment]
Cool! I see it now. Added a garden. One note, on creation the title I gave it was not set. After editing, and reentering the name, the title was visible. But this should be a separate bug ;)
