### ISSUE TITLE
Copyright and author tags in /meta/_global.html.erb

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#300]
This should be quick, the format is already there. 

I'm not sure what publisher name should be @mo22de?

**Comment by warpling** [comment]
Currently we have ```	
    <!-- <meta name="copyright" content="fixed 2013 - actual-year-variable [dynamic here!], organisation, license-name, license-link" />```

I think author only belongs in guides ([Google explanation](https://support.google.com/webmasters/answer/79812?hl=en))?
Copyright seems pretty straight forward?…

**Comment by simonv3** [comment]
There's a reason this is tagged as low hanging fruit :P
