### ISSUE TITLE
Verify email addresses upon account creation

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#353]
For security purposes to:

1) Not get spammed with a zillion fauxcounts
2) Not allow someone to register with someone else's email and opt them in to our mailing list/prevent the real person from signing up/pretending to be the real person.

**Comment by simonv3** [comment]
So, I'm in the middle of doing this, but we'll need a migration of current users in the mean time. Putting this here to remind myself to do that when we roll this on to live. https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users
