### ISSUE TITLE
Increase Max File Size for Images

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#396]
I'm getting errors when trying to upload an image larger than 2MB. I think a good maximum size is 5MB for quality high-res images.

From the console:

`"<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>2099915</ProposedSize><MaxSizeAllowed>2097152</MaxSizeAllowed><RequestId>FEAC427E4FCBA95E</RequestId><HostId>6RMdxY7fjDauUVcqTX//gqE03HZPpIGlMMzxzrJoJJZvw9T0ierLb41uO/dAg1jYGJQoDOEeqpA=</HostId></Error>"`

**Comment by simonv3** [comment]
Most pictures I take on my phone are larger than the 2 MB limit (often larger than 5 MB even). However, most of those pictures aren't actually of that quality. I wonder what size limitations AirBnB has?

**Comment by roryaronson** [comment]
Hmm good point, I imagine mobile uploading will be heavily used. Looking at my phone's photos,  the first I checked (simple photo with a lot of sky) was 5.6MB, the second was 10.1MB (a complex photo of my backyard).

Maybe something like 15 or 20MB max?

**Comment by rickcarlino** [comment]
I set that a while back- I can change it to something larger, but will need to do some resizing / thumb-a-matizing on the job worker when we post process.

**Comment by simonv3** [comment]
I don't know whether we should be storing 10/20 MB pictures, a 400 KB jpeg is often good enough for a screen of even the largest resolution (it would also increase loading times for our websites massively). post upload processing seems like a good idea.

**Comment by roryaronson** [comment]
Yea I agree we don't need to store or serve up full resolution files. But if I'm trying to upload from my phone, the image worker should just deal with it rather than making me resize the image file.

**Comment by RickCarlino** [comment]
We can definitely do a post processing resize down to something smaller on the backend. I will give it a shot this week.

**Comment by roryaronson** [comment]
@RickCarlino any updates on this one?

**Comment by roryaronson** [comment]
I'd like to bump this one so I can upload more Crop images, and so smart phone pictures don't need resizing.
