### ISSUE TITLE
Add Crop Page Redirect Logic

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#398]
When I go to create a guide for a Crop that does not yet exist, I am suggested to create the Crop. I do so, and click save, and get redirected to the Guide creation flow with the Crop field auto filled for me. Awesome. 

When I search for a Crop, and it doesn't exist, I can press the 'add crop' button and add it. Upon clicking save I get redirected to the guide creation flow. This is confusing. From this flow, I was expecting and wanted to see my newly created Crop page.

Some logic could redirect the user to the more appropriate place after adding the crop, taking into account the context of the flow they're in.

**Comment by simonv3** [comment]
This could be fixed by passing a paramater through GET that dictates the direction of the Create controller.
