### ISSUE TITLE
Images don't respect aspect ratio on Guides or Crops

### ISSUE THREAD

**Issue by warpling** [openfarmcc/OpenFarm#399]
We'll need to either use `background-image` to cover position the photo, or use ImageMagik on the back-end to make sure we have certain cropped aspect ratios.

**Comment by simonv3** [comment]
:+1:

**Comment by simonv3** [comment]
@RickCarlino I've spent some time fiddling with imagemagick, but can't seem to get it to properly crop a small image. Any thoughts?

**Comment by RickCarlino** [comment]
Which page is this on? We probably just need to change the geometry settings in `picture.rb` or make a new version of the attachment.

What would be ideal for this image? What is the ideal height / width?

**Comment by roryaronson** [comment]
@simonv3 can this one be closed?

**Comment by warpling** [comment]
Think so


~Ryan
