### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by growdigital** [openfarmcc/OpenFarm#406]
"helps developers define and maintain consistent coding styles between different editors and IDEs"

http://editorconfig.org/

**Comment by simonv3** [comment]
Why close?

**Comment by growdigital** [comment]
Oops, an errant mouse click! Meant to edit and say: creating a pull request

**Comment by growdigital** [comment]
How do yo

**Comment by simonv3** [comment]
Yeah those two buttons are confusing
