### ISSUE TITLE
Create modular styles for crop page

### ISSUE THREAD

**Issue by growdigital** [openfarmcc/OpenFarm#409]
Create modular CSS using BEM syntax for crop pages as a test.
eg https://openfarm.cc/en/crops/cherry-tomatoes

Outline of approach on Slack:
https://openfarm.slack.com/files/growdigital/F03B71VBB/Growing_a_crop_page_with_modular_CSS.md

Branch what I have created:
https://github.com/growdigital/OpenFarm/tree/409-modular-crop

**Comment by simonv3** [comment]
Just for the record I copied the slack file to the wiki: 

https://github.com/openfarmcc/OpenFarm/wiki/Modular-CSS-(by-@growdigital)

We can hash things out there a bit more. I'm about to do a PR that goes some way to restructuring things (we were already fairly modular thanks to a restructure @warpling did a while ago, so it wasn't that hard). Basically what it does is bring big bucket things into `components`, from which we can start refactoring into sub-modules (like you mention) and brings some things together under `ui`.
