### ISSUE TITLE
Subscribe to Newsletter on User creation flow does not work

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#410]
Mailchimp receives no email address and Active Admin shows that the boolean has not been switched to true.

**Comment by simonv3** [comment]
The boolean for this should now be set, the next step is adding things to Mailchimp via their API. This could get interesting.

**Comment by simonv3** [comment]
https://github.com/amro/gibbon

**Comment by roryaronson** [comment]
When tackling this, probably best to do #541 too
