### ISSUE TITLE
Change "Requirements" to "Basic Needs"

### ISSUE THREAD

**Issue by warpling** [openfarmcc/OpenFarm#426]
@roryaronson made a good point that "Basic Needs" is probably a more approachable way to word this. We should consider changing our strings. Thoughts?

**Comment by simonv3** [comment]
Agreed. I was going to comment on this yesterday.

**Comment by simonv3** [comment]
I've changed the en.yml for this, but we should probably also change our actual variables (class names in html) to make this easier to find).

**Comment by warpling** [comment]
Thanks Simon. I never got this one in. Agreed on the variables.
