### ISSUE TITLE
An excel file with our current en.yml file, and let people add other translations

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#429]
So that they don't have to work on code.

**Comment by warpling** [comment]
That was thoughtful

**Comment by md5** [comment]
You guys might want to look at TranslateWiki. iNaturalist started using it
recently for their translations.

**Comment by simonv3** [comment]
@md5 That's interesting. I'm looking at the export options for the wiki, and it doesn't seem to be working for me. Do you know if it's at all ruby friendly? (yml). From what I see from the export stuff in the FAQ, it's concerned mainly with PHP.

**Comment by md5** [comment]
@simonv3 the reason I suggested TranslateWiki is that iNat is also using Rails i18n and I figured they'd worked out some way to use it that works well.

Looks like this is the discussion around getting them set up: https://translatewiki.net/wiki/Thread:Support/Getting_iNaturalist.org_registered_on_translatewiki

**Comment by simonv3** [comment]
Cool, thanks, that actually looks like a really useful checklist as well for our translations (lego, arbitrary HTML, etc).

**Comment by md5** [comment]
@loarie: hope you don't mind me pinging you, but do you have any advice for the OpenFarm guys about how you've made it easier for translators to contribute to iNat?

**Comment by loarie** [comment]
hi guys - happy to answer any questions - we're trying translatewiki and crowdin details here: http://www.inaturalist.org/pages/translate we haven't completed the circle of deploying any of the contributed translations yet - but its been surprisingly cool to see all the unsolicited volunteer activity

**Comment by md5** [comment]
Thanks @loarie!

Did you guys happen to come across any solutions for contextual translation when looking at the available options?

Since the OpenFarm app is actually a hybrid Angular/Rails app from my understanding, I actually found this interesting article regarding using a commercial platform call PhraseApp to do contextual translations of Angular apps: http://localize-software.phraseapp.com/posts/angularjs-translating-angularjs-applications-in-context-with-angular-phrase/

I'd be curious to see if they'd be willing to donate or discount use of their platform for nonprofit use, though they are based in Germany and probably wouldn't get a tax benefit donating to U.S.-based nonprofits.

**Comment by loarie** [comment]
we didn't we're ignoring the JS translations with the translate wiki stuff which is prob not wise

**Comment by roryaronson** [comment]
Another option is [crowdcrafting.org](http://crowdcrafting.org/). I know the folks behind the project and they have offered to help us setup a translation project. We can specify how much redundancy we want (if any) and I think have the system can auto output new yml files for us.

**Comment by simonv3** [comment]
@roryaronson any word from the crowdcraft people?

**Comment by roryaronson** [comment]
I just put in [another word on their repo](https://github.com/PyBossa/pbs/issues/8#issuecomment-71153559). We can do some short term translating now with a spreadsheet if that's strategic. I can put together a spreadsheet and send an email newsletter out asking for help with it. Could be pretty cool to see 100 people on one spreadsheet at once ;)

**Comment by roryaronson** [comment]
I guess [transifex](https://www.transifex.com/projects/p/openfarm/) solves this for us!
