### ISSUE TITLE
'My Guides' Manager

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#435]
Several folks have emailed me today saying they started Guides with intention to fill them out over a season (once they have got the right photos and info). They said they *could* navigate back to their Guide, but only in the roundabout way of finding it through search results.

Just like we have a 'My Gardens' page, we could have a 'My Guides' page. Right now it can just show stuff like the Guide's name (with a link), the Crop it is for, the day it was published, when it was last updated, and links to delete and edit the Guide.

**Comment by simonv3** [comment]
I'm just going to add a link to `/en/guides/` for now which will just show the user's guides, the crop for each guide, and edit links.

We don't have updated and published values! (I think). Oops.

**Comment by roryaronson** [comment]
That shows all guides though... Are you modifying that page too?

**Comment by simonv3** [comment]
Yeah
