### ISSUE TITLE
Sort Guides by Compatibility

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#438]
Woo!!! Compatibility scores are working, now they should be weighted in the search results. This is probably an elasticsearch thang?
![screenshot 2015-01-19 at 2 43 25 pm](https://cloud.githubusercontent.com/assets/5524043/5809136/f2fc84d0-9fe9-11e4-9438-3f2ac5c0d87c.png)

**Comment by simonv3** [comment]
I tried but I got no idea how to do this. @RickCarlino @richleland?
