### ISSUE TITLE
SIte-wide footer?

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#439]
One person mentioned in an email to me that they wanted the footer links accessible from every page. Essentially they had seen the links, were navigating the site, then wanted to click one but couldn't find them or remember that they first saw them on the homepage.

So, we could do the footer site-wide? Not sure how that would work with the split screen view, or if it is otherwise distracting for the majority of users.

Thoughts?

**Comment by simonv3** [comment]
Footers with infinite scroll is a pet-peeve of mine. Though we could probably figure out a way to make that less annoying.

**Comment by simonv3** [comment]
I thought this was a low-hanging-fruit, but I was wrong. Copied form slack:

Okay, I'm going to back-pedal on the footer thing until someone who knows a bit more (ryan) about how the crop and crop_search pages are laid out can have a look at it. At the moment any footer on those pages creates a nested scrollbar situation. We could disable the footer on those two pages specifically but I'm hesitant to do even more if statements on a wrapper like that (cause it would already have to exist on the home page, which has 100% height elements on it as well).

**Comment by warpling** [comment]
Sorry I never got to this. The footer is commented out right now, is that for me to check out?

**Comment by simonv3** [comment]
Yeah, I'm just not sure what to do with it on the crop search and view page.
