### ISSUE TITLE
Basic Needs Compatibility is buggy

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#440]
I have only one Garden, with 'Full Sun'. If I go to one guide with the 'Full Sun' Basic Need, it says I'm compatibile. If I go to another Guide also with the 'Full Sun' Basic Need, it says I'm not compatible because 'I have Partial Sun' according to the tooltip.

Hmmm?

**Comment by simonv3** [comment]
What are the two guides?
