### ISSUE TITLE
Users Want Multiple Gardens

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#443]
Several emails now included this request, wahoo!

**Comment by simonv3** [comment]
Alright. I built that functionality out last night. I'll make it more thorough today.

**Comment by simonv3** [comment]
Actually going to spend about 20 minutes on this right now. Should we roll multiple gardens out even if they don't factor into guide compatibility scores yet? (I think yes, since compatibility scores are still fairly buggy).

**Comment by warpling** [comment]
Maybe where the most compatible is the shown score? :/


~Ryan

**Comment by roryaronson** [comment]
I agree with Ryan. If a user has multiple gardens, we should show the score for the garden the guide is most compatible with. Maybe a tooltip over the score can specify which garden it is compatible with.

Eventually there will need to be a way for users to say 'I want scores for only garden X', maybe via some search filter such as 'For Planting in Garden: _____dropdown of gardens____'
