### ISSUE TITLE
Everyone wants to edit Crops

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#444]
One guy started adding a Crop, then saved it. He then went outside to take a photo and wanted to add it, but was not able to edit the Crop because he is not an admin. :(

So for anyone to be able to edit Crops, we need some type of roll-back feature/history, to protect against unwanted deletions, yea?

**Comment by simonv3** [comment]
Well, not as much deletions as overwriting. You can't delete crops on the site at the moment. If we're not concerned about overwriting, I can just remove that check.

That is pretty awesome though.

**Comment by roryaronson** [comment]
I think we should remove that check. Wikipedia has plenty of 'edit wars' and its what makes it great. Not that I think our users will get into an edit war, but I don't think we should be too concerned with malicious activity atm.

**Comment by simonv3** [comment]
Okay, I will remove the check, and then create a separate issue for history tracking on crops.
