### ISSUE TITLE
Display measurement units.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#453]
I propose that the units used on the site be stored as metric, and converted to a user's preference on page load. 

Thoughts?

**Comment by roryaronson** [comment]
Agreed! And if a user wants to enter in values in English, then we convert and store it as metric.

**Comment by simonv3** [comment]
Yep.

**Comment by warpling** [comment]
Is there a more proper way to i18n this than just appending a translate string? Is that how the :earth_asia:  does it?
