### ISSUE TITLE
Adding Crops to a Garden (without a Guide)

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#456]
Some people want to add Crops to their Garden but there are no Guides written for those Crops yet. Also, some people do not want to be following a specific Guide, rather they will track the progress of the Crop themselves.

Perhaps there could be the same 'Add to Garden' dropdown on Crop pages? It would essentially do the same thing as the one on Guide pages, except there would be no data for the 'Guide' field.

**Comment by simonv3** [comment]
That should be pretty simple.

**Comment by simonv3** [comment]
This is live on staging. Was brought in with the #471.
