### ISSUE TITLE
Bad copy in "agree to…" warning

### ISSUE THREAD

**Issue by warpling** [openfarmcc/OpenFarm#464]
![screen shot 2015-01-22 at 11 24 44 am](https://cloud.githubusercontent.com/assets/220240/5862787/6c52853c-a229-11e4-8537-dbcf5f164e82.png)

**Comment by warpling** [comment]
[These are kind of strange solutions](http://stackoverflow.com/questions/808547/fully-custom-validation-error-message-with-rails) imo.

**Comment by simonv3** [comment]
Yeah I think this is happening because of a badly formatted flash message generated by mutations, basically just saying that agree is missing, and then the actual message.
