### ISSUE TITLE
Embed a `UserSetting` class

### ISSUE THREAD

**Issue by RickCarlino** [openfarmcc/OpenFarm#465]
We're starting to put one-off fields for user preference settings into the User model, but that might get out of hand fast.

It would be good for us to make sure users `have_on :user_setting`. We could probably do this to prevent nil exceptions:

```ruby
def user_settings
  super || Setting.create(user: self)
end
```

**Comment by simonv3** [comment]
There is now a user setting class on the server. Next step on this is to migrate data across from the user to the user setting class. Then we should probably see how removing some of these things breaks.
