### ISSUE TITLE
Guide step actions still have Latin descriptions

### ISSUE THREAD

**Issue by warpling** [openfarmcc/OpenFarm#466]
Do you speak Latin? 

![screen shot 2015-01-22 at 11 53 47 am](https://cloud.githubusercontent.com/assets/220240/5863451/851fa964-a22e-11e4-9b5f-0500c69f61d4.png)

**Comment by simonv3** [comment]
Can we rename this to "Come up with descriptions for stages" because the latin is only on localhost? Also, did kevin come up with some?

**Comment by warpling** [comment]
[Kevin did](https://docs.google.com/spreadsheets/d/11J7VIrVCyhS_Uk0NF0l9PenZMgyX7-40UEKSbXJzYt0/edit?usp=docs_home)! I forgot to put them in though!

**Comment by warpling** [comment]
Doing it now.

**Comment by simonv3** [comment]
Yuss!

**Comment by warpling** [comment]
Done! Thanks @xbertolerox!
