### ISSUE TITLE
Interactive Stage builder

### ISSUE THREAD

**Issue by warpling** [openfarmcc/OpenFarm#468]
Currently certain actions are rigidly provided for each stage. We must build a tool for adding/removing/ordering actions per step.

@roryaronson :
"Currently we're listing on the left side all of the Actions that *we think* are relevant to the Life Stage. As a Guide Creator, seeing all the Actions like that feels overwhelming now, and we're only going to be adding more possible Actions. Also, by listing them all out in this way, I feel that I *have to* fill them out, that I didn't really get to choose which ones I want - it feels bad to have them there but leave them empty. I think a better interface for adding Actions is a button to 'Add an Action'. This would bring up a modal with all of the Actions OpenFarm supports, including 'Other'. Based on the Life Stage, we can have a 'Recommended Actions' section and an 'All Actions' section in the modal - maybe even a search function for quick selection for power users! Because sure, maybe it doesn't make sense *to us* to do a scarification action during the adult stage, but that's cause we're not the experts. I think we should let our users have full control over crafting their Guide by making all actions available to every life stage. I'll make a mockup right now to elaborate on the idea (edited)

Also, I think it will be important for Actions to have optional ordering. ie: 1st do this, 2nd do that, 3rd do this other thing.  And do these two things whenever you want."

![add_actions_modal_1024](https://cloud.githubusercontent.com/assets/220240/5865628/acb3808e-a23f-11e4-8f41-02646c224adb.png)

**Comment by roryaronson** [comment]
Simon and I are working on this one

**Comment by roryaronson** [comment]
Simon, I just checked out your work - it looks awesome and works really well. I'm going to add some minor style tweaks, but for the most part I think this is done! :+1:
