### ISSUE TITLE
"Create Your First Garden" button doesn't change after creating a garden

### ISSUE THREAD

**Issue by xbertolerox** [openfarmcc/OpenFarm#472]
I created my "first" garden, and the green button below my gardens hasn't changed. It still says "Create Your First Garden" even after creating my first garden. It should say something like, "Add Another Garden" 
![screen shot 2015-01-27 at 3 26 47 pm](https://cloud.githubusercontent.com/assets/10620877/5929475/f933d7a4-a638-11e4-9598-88ad71ba791b.png)

**Comment by simonv3** [comment]
:+1:
