### ISSUE TITLE
Add 'Create your first guide' button to the My Guides page if the user has not made any guides yet

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#478]

**Comment by roryaronson** [comment]
And if the user has created guides, change the button to 'Create a new guide'

**Comment by simonv3** [comment]
As a result, should we remove the "Create a new guide" from the drop down? I don't think we're there yet, but we might be cluttering up that menu.

**Comment by roryaronson** [comment]
I think we should keep it for now, but yea at some point that menu will need an overhaul
