### ISSUE TITLE
undefined 500 when uploading image locally

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#483]
Console nonsense:

```
edit:1 GET http://localhost:3000/en/crops/cherry/[] 404 (Not Found)
angular.js?body=1:81 GET http://localhost:3000/api/aws/s3_access_token 500 (Internal Server Error)angular.js?body=1:81 (anonymous function)angular.js?body=1:76 tangular.js?body=1:74 fangular.js?body=1:101 (anonymous function)angular.js?body=1:115 g.$evalangular.js?body=1:112 g.$digestangular.js?body=1:116 g.$applyngs3upload.js?body=1:223 uploadFilengs3upload.js?body=1:269 (anonymous function)jquery.js?body=1:4642 jQuery.event.dispatchjquery.js?body=1:4310 elemData.handle
angular.js?body=1:95 Error: Can't receive the needed options for S3 TypeError at /api/aws/s3_access_token
=====================================

> no implicit conversion of nil into String

app/controllers/api/aws_controller.rb, line 30
----------------------------------------------

``` ruby
   25       end
   26   
   27       def s3_upload_signature
   28         # Notice the gsub("\n", ''). Holy cow you will be frustrated if you forget
   29         # to strip out the carriage return. AWS gives cryptic errors.
>  30         Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest::Digest.new('sha1'),
   31                         ENV['S3_SECRET_KEY'],
   32                         s3_upload_policy)).gsub("\n",'')
   33       end
   34     end
   35   end
```

App backtrace
-------------

 - app/controllers/api/aws_controller.rb:30:in `digest'
 - app/controllers/api/aws_controller.rb:30:in `s3_upload_signature'
 - app/controllers/api/aws_controller.rb:7:in `s3_access_token'

Full backtrace
--------------

 - app/controllers/api/aws_controller.rb:30:in `digest'
 - app/controllers/api/aws_controller.rb:30:in `s3_upload_signature'
 - app/controllers/api/aws_controller.rb:7:in `s3_access_token'
 - actionpack (4.0.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 - actionpack (4.0.2) lib/abstract_controller/base.rb:189:in `process_action'
 - actionpack (4.0.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
 - actionpack (4.0.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
 - activesupport (4.0.2) lib/active_support/callbacks.rb:393:in `_run__3154961910721122262__process_action__callbacks'
 - activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
 - actionpack (4.0.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
 - actionpack (4.0.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
 - actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
 - activesupport (4.0.2) lib/active_support/notifications.rb:159:in `block in instrument'
 - activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 - activesupport (4.0.2) lib/active_support/notifications.rb:159:in `instrument'
 - actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 - actionpack (4.0.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 - searchkick (0.8.5) lib/searchkick/logging.rb:107:in `process_action'
 - actionpack (4.0.2) lib/abstract_controller/base.rb:136:in `process'
 - actionpack (4.0.2) lib/abstract_controller/rendering.rb:44:in `process'
 - actionpack (4.0.2) lib/action_controller/metal.rb:195:in `dispatch'
 - actionpack (4.0.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 - actionpack (4.0.2) lib/action_controller/metal.rb:231:in `block in action'
 - actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
 - actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
 - actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
 - actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in `block in call'
 - actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `each'
 - actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `call'
 - actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
 - rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
 - rack-attack (4.2.0) lib/rack/attack.rb:97:in `call'
 - warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
 - warden (1.2.3) lib/warden/manager.rb:34:in `catch'
 - warden (1.2.3) lib/warden/manager.rb:34:in `call'
 - rack (1.5.2) lib/rack/etag.rb:23:in `call'
 - rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
 - rack (1.5.2) lib/rack/head.rb:11:in `call'
 - remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/flash.rb:241:in `call'
 - rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
 - rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/cookies.rb:486:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 - activesupport (4.0.2) lib/active_support/callbacks.rb:373:in `_run__3745565137594316036__call__callbacks'
 - activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
 - actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/reloader.rb:64:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 - railties (4.0.2) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (4.0.2) lib/rails/rack/logger.rb:20:in `block in call'
 - activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `block in tagged'
 - activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in `tagged'
 - activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `tagged'
 - railties (4.0.2) lib/rails/rack/logger.rb:20:in `call'
 - quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
 - actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 - rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
 - rack (1.5.2) lib/rack/runtime.rb:17:in `call'
 - activesupport (4.0.2) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
 - rack (1.5.2) lib/rack/lock.rb:17:in `call'
 - actionpack (4.0.2) lib/action_dispatch/middleware/static.rb:64:in `call'
 - rack-cors (0.3.1) lib/rack/cors.rb:72:in `call'
 - rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
 - railties (4.0.2) lib/rails/engine.rb:511:in `call'
 - railties (4.0.2) lib/rails/application.rb:97:in `call'
 - rack (1.5.2) lib/rack/content_length.rb:14:in `call'
 - thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
 - thin (1.6.3) lib/thin/connection.rb:84:in `catch'
 - thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
 - thin (1.6.3) lib/thin/connection.rb:53:in `process'
 - thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
 - eventmachine (1.0.4) lib/eventmachine.rb:187:in `run_machine'
 - eventmachine (1.0.4) lib/eventmachine.rb:187:in `run'
 - thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
 - thin (1.6.3) lib/thin/server.rb:162:in `start'
 - rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
 - rack (1.5.2) lib/rack/server.rb:264:in `start'
 - railties (4.0.2) lib/rails/commands/server.rb:84:in `start'
 - railties (4.0.2) lib/rails/commands.rb:76:in `block in <top (required)>'
 - railties (4.0.2) lib/rails/commands.rb:71:in `tap'
 - railties (4.0.2) lib/rails/commands.rb:71:in `<top (required)>'
 - bin/rails:4:in `require'
 - bin/rails:4:in `<main>'

    at Error (native)
    at http://localhost:3000/assets/angular-libs/ngs3upload.js?body=1:261:77
    at http://localhost:3000/assets/angular/angular.js?body=1:101:493
    at g.$eval (http://localhost:3000/assets/angular/angular.js?body=1:115:336)
    at g.$digest (http://localhost:3000/assets/angular/angular.js?body=1:112:411)
    at g.$apply (http://localhost:3000/assets/angular/angular.js?body=1:116:157)
    at p (http://localhost:3000/assets/angular/angular.js?body=1:75:223)
    at y (http://localhost:3000/assets/angular/angular.js?body=1:80:8)
    at XMLHttpRequest.u.onreadystatechange (http://localhost:3000/assets/angular/angular.js?body=1:81:75)angular.js?body=1:95 (anonymous function)angular.js?body=1:70 (anonymous function)angular.js?body=1:102 (anonymous function)angular.js?body=1:115 g.$evalangular.js?body=1:112 g.$digestangular.js?body=1:116 g.$applyangular.js?body=1:75 pangular.js?body=1:80 yangular.js?body=1:81 u.onreadystatechange
```

**Comment by RickCarlino** [comment]
Something is not right with that URL. @simonv3 do you have any idea why there is an empty `[]` at the end of the URL?

This part of the codebase hasn't been changed in a very long time, and I don't think that the ENVs have changed, either. Maybe its related to whatever script is generating that URL? I can take a look a little bit later day.

**Comment by simonv3** [comment]
I'll poke a little deeper. @roryaronson do you by any chance remember how you got to the page? (crop search, direct access, etc).

**Comment by roryaronson** [comment]
I think I just clicked the community favorite, then edit crop, then tried to upload a photo. The URL in my browser of the crop edit page was normal. (...tomatoes/edit)

**Comment by simonv3** [comment]
^That's totally just a mis-reference to a github issue. Should have been #481
