### ISSUE TITLE
Verify OpenFarm for Pinterest

### ISSUE THREAD

**Issue by xbertolerox** [openfarmcc/OpenFarm#486]
I created a Pinterest for OpenFarm. I want to have our account/website verified. Verified sites show up on profile and in search results. To verify, add this meta tag to the <head> of your index.html file or equivalent

~~~
<meta name="p:domain_verify" content="cd2adeb2844c48f6ed896a1a627b6fb9"/>
~~~

Thanks team!

**Comment by md5** [comment]
I'd probably go the separate file route as opposed to the `<meta>` route if I were to do this. cf. https://help.pinterest.com/en/articles/verify-your-website

**Comment by xbertolerox** [comment]
If that's the preferred route, here is the file for the second option https://www.dropbox.com/s/p9tlshhtjv3esvn/pinterest-cd2ad.html?dl=0

**Comment by simonv3** [comment]
@md5 Why would you take that route?

**Comment by md5** [comment]
I think a standalone file under `public` is less likely to get messed up by someone wanting to change other things.

**Comment by simonv3** [comment]
We currently have all of our social media stuff in [`meta/_social_network.html.erb`](https://github.com/openfarmcc/OpenFarm/blob/master/app/views/meta/_social_network.html.erb) though, I don't know whether making an exception for Pinterest makes much sense.

**Comment by md5** [comment]
I'll go back about my business then :)

**Comment by simonv3** [comment]
This is on staging at the moment.
