### ISSUE TITLE
Bug: Add crop button not working

### ISSUE THREAD

**Issue by jbernardo95** [openfarmcc/OpenFarm#491]
![screen shot 2015-02-10 at 12 31 50](https://cloud.githubusercontent.com/assets/6342528/6127260/edf5b180-b120-11e4-8ac2-59e8bb6804d3.png)

**Comment by simonv3** [comment]
Hey @jbernardo95, that looks like you're trying to create a crop while not signed in, can you try signing in and then creating the crop? For now we require people to be signed in to OpenFarm to create a crop. We should probably indicate that better though, thanks for pointing it out.

**Comment by jbernardo95** [comment]
Yep, that's probably it.
Hide it when the user is not signed in

**Comment by warpling** [comment]
Or redirect it to the sign up flow with an explanatory alert!

**Comment by jbernardo95** [comment]
That will work too, and it is better solution
