### ISSUE TITLE
What happens to a user's Guides when they cancel their account?

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#499]
I think they should remain on the site, and the by-line should just no longer link to anything. Perhaps a tooltip can show up over the name that says "This user has cancelled their OpenFarm account"

Thoughts?

**Comment by simonv3** [comment]
Their name should probably be removed as well, just for privacy's sake.

I think the guides should be kept, because by creating them they're put in the public domain. Is that in our terms and conditions?

**Comment by roryaronson** [comment]
This is interesting from Wikipedia: "Due to all contributions being licensed under the CC BY-SA 3.0 License and the GFDL, it is not possible to delete an account." One can only change their username and make their user page private, but they can't remove a username altogether.

I think its a nice courtesy to change the by-line to "inactive member"

**Comment by guitsaru** [comment]
With CC0 having their username removed isn't a problem like it is with CC BY-SA 3.0.  I think allowing account deletion and showing something like "by a former contributer" when no account is present is fine.

**Comment by roryaronson** [comment]
+1

**Comment by simonv3** [comment]
I *think* this now works as of #617. We check for user display name to exist. 

There's probably a more elegant way to do this.
