### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#510]
Picking up where the discussion left off in #505. I made another iteration of a timeline mockup. Notable changes:
* The bars for the guide being followed starting today is more distinctly separate from the "growing season" bars which shows more of a window of opportunity for the plant
* Tooltips, tooltips, tooltips!
* Adjusted the subtext next to the 'Timeline' header to reflect the fact that the timeline is dplayed as though the user will be starting to follow the guide today.

Feedback and other design ideas welcome! I'll try and whip something together for timeline creation tomorrow.

![more timeline ideas 3](https://cloud.githubusercontent.com/assets/5524043/6410173/946c56ec-be21-11e4-9390-cbd14cd43ae7.png)

**Comment by emily-plummer** [comment]
So is the "Plant's Lifetime" section referring to when you actually planted the crop, vs the window section is when you think people could possibly plant the crop?

**Comment by roryaronson** [comment]
Yes almost. The plant's lifetime isn't necessarily historical data from when you actually planted the plant. Its more of a projection/forecast saying 'if you actually planted this today, this is how long it will take'. You got the window section spot on.

**Comment by roryaronson** [comment]
I imagine the tooltips of the time bar options will explain that in more detail

**Comment by md5** [comment]
I haven't tried looking at the site on a tablet myself, but be careful with tooltips and hovers since they can be a problem when it comes to touch-screen user experience.

**Comment by roryaronson** [comment]
How can it be a problem? Inadvertant touches? Lack of 'hoverimg' makes it less intuitive to activate the tooltips?

Perhaps if we can detect a tablet interface, we can explicitly tell the user to click things for more info.

**Comment by emily-plummer** [comment]
OOOOOH this all makes sense now!

**Comment by md5** [comment]
> How can it be a problem? Inadvertant touches? Lack of 'hoverimg' makes it less intuitive to activate the tooltips?

Exactly. Unless you want to have tooltip trigger buttons all over the place or something.

**Comment by roryaronson** [comment]
Can't the elements themselves be the trigger buttons?

**Comment by md5** [comment]
Sure. That seems reasonable in this case.

**Comment by roryaronson** [comment]
Hey all, I've made a mockup for Timeline Creation, which will be a step in Guide Creation just before the end. The flow is focused on walking the author through the process so as to teach them what it means and to not overwhelm them with too many things to adjust at once. Looking forward to your feedback:

![timeline creation 1](https://cloud.githubusercontent.com/assets/5524043/6424813/50c381bc-bebd-11e4-8ee8-d6a512edda6c.png)

**Comment by roryaronson** [comment]
See now: Guide Creation Flow V2 (with integrated/tweaked Timeline building) #638
