### ISSUE TITLE
Make reindexing of guides way more efficient

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#518]
It currently takes about 2 minutes to do each guide. That is not scalable.

**Comment by RickCarlino** [comment]
Were you reindexing 1 guide, or the entire database?

**Comment by simonv3** [comment]
1 Guide, and the compatibility scores for each user:

https://github.com/openfarmcc/OpenFarm/pull/495

**Comment by guitsaru** [comment]
I'm going to be taking a look at this in the next day or two.  I've just been busy lately.

**Comment by m3talsmith** [comment]
It looks like a fix was merged. Should this be closed?
