### ISSUE TITLE
Bring the footer back

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#536]
A few Kickstarter backers have asked me via Kickstarter how to contact us, citing specifically that we should have a site footer ;p

**Comment by warpling** [comment]
Okay, basically the blocker was that on crop pages there are two scroll-able areas (the crop info and the guide list), and there isn't an easy way to keep both scrollable with the footer beneath them, without shrinking both of them vertically to make room (discussed a bit in #439). I propose making both sections not individually scrollable and to use [Foundation's Equalizer](http://foundation.zurb.com/docs/components/equalizer.html) to make them equal height, putting the footer beneath them. The sections will no longer being individually scrollable, but this way the footer will behave the same on every page and we won't have the double-scrolling crop/guide list that haunts me as a decision to this day.

**Comment by simonv3** [comment]
Thanks for the research on this @warpling, are you going to give it a shot?

**Comment by warpling** [comment]
If the above sounds good to you!

**Comment by simonv3** [comment]
yep!

**Comment by roryaronson** [comment]
:+1: Thanks Ryan
