### ISSUE TITLE
Style Alerts

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#539]
Alerts are kind of obtrusive right now, usually block page titles, and sometimes break styling by pushing everything down awkwardly. We'll also want to add alerts for when users earn badges, and potentially more 'rich' alerts that have calls to action. Here is a mockup for what growl style alerts could look like for us. Thoughts and feedback are welcome!

![alerts](https://cloud.githubusercontent.com/assets/5524043/6592824/95d6560a-c78f-11e4-8ecc-c5f7f38cb598.png)

**Comment by simonv3** [comment]
I think growl is great - but we should be taking advantage of literally the one thing Angular is meant for and doing inline form validation on sign in and sign up (and form fields in general).
