### ISSUE TITLE
Add optional field to email newsletter signup for the person's name

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#541]
Requested by Kevin so that emails can include the user's name to be more personal.

**Comment by simonv3** [comment]
Is this on the [mailing-list sign up page](https://openfarm.cc/pages/mailing-list) or on account creation flow? If it's on account creation flow, can we just substitute the user's display name?

**Comment by roryaronson** [comment]
Ah, so on the mailing list signup page we should add the name field. And on account creation we should send mailchimp the display name

**Comment by simonv3** [comment]
This is on staging, and I'll roll it out today.
