### ISSUE TITLE
Add more locale files

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#543]
Simon set us up with this cool service for anyone to help us translate the site: https://www.transifex.com/projects/p/openfarm/

It looks like we need to add stub .yml files for every language we want. Can you confirm this @simonv3?

Once we have that, we can send out a newsletter to our users asking them to help us translate!

**Comment by simonv3** [comment]
Actually, I think there's nothing we have to do until there is a completed translation on transifex for a language or locale.

We can list what other translations we want to be available on there, but I think that anyone can request to add languages and then create translations for them.

The French and South African English were requested by an outsider (don't know who).

**Comment by roryaronson** [comment]
Hmmm, ok I just requested Armenian, and it just shows me that the request has been made, but no option to approve the request. Does a PR have to happen for it to be added?

**Comment by roryaronson** [comment]
Let's get moving on this one. I'll add more languages on Transifex. Should we try out machine translation or ask our newsletter subscribers?

**Comment by simonv3** [comment]
I tried to do machine translation, but couldn't find how to do it. Can you do it for a couple of languages?

**Comment by roryaronson** [comment]
Ergg this is annoying. I got machine translation to work (had to sign up for a Translate API key from Google), but I have to manually machine translate each string. Ie: press a button to 'machine translate' something and then accept the translation. I can't find how to just machine translate all....

**Comment by roryaronson** [comment]
Scratch that. Figured it out! Just had to select all the strings in the list and press machine translate. Its slow though... like it goes 1 at a time at a speed of like 2/second. Chugging through French right now

**Comment by simonv3** [comment]
So, I would love to see some usability research on just throwing these on the site. Should we first get people to double check them?




I’ve used google translate for Vietnamese, and half of the time it doesn’t make sense.


—

**Comment by roryaronson** [comment]
Alright, we have 50 languages 100% machine translated in transifex. We can push them to live when we feel ready (either #yolo or after we get them reviewed I guess)

**Comment by simonv3** [comment]
I’ll copy the nl stuff to push it live, that’s fairly complete I think. 

—
