### ISSUE TITLE
Add images for wiki (not a bug, an enhancement request, or a question... just a hack)

### ISSUE THREAD

**Issue by DavidMGross** [openfarmcc/OpenFarm#545]
By adding images to an issue like this, I can then reference their URLs on the wiki. Why I can't just upload them to the wiki is beyond my understanding.
![addcorsconfiguration](https://cloud.githubusercontent.com/assets/4491168/6646919/b39599c8-c986-11e4-937e-c48f7a426f5f.png)
![attachpolicy](https://cloud.githubusercontent.com/assets/4491168/6646920/b398eee8-c986-11e4-9fbe-067ad3014d8b.png)
![corsconfigurationeditor](https://cloud.githubusercontent.com/assets/4491168/6646921/b39e53ce-c986-11e4-9db0-1b67ee9ac21a.png)
![createuser](https://cloud.githubusercontent.com/assets/4491168/6646922/b3a0fcf0-c986-11e4-91f8-99eed1b6380d.png)
![getstartedwithiamusers](https://cloud.githubusercontent.com/assets/4491168/6646923/b3a9ca7e-c986-11e4-91c5-cdde989ada9b.png)
![securitycredentials](https://cloud.githubusercontent.com/assets/4491168/6646924/b3ace984-c986-11e4-875e-471f8b78d09a.png)
![showusersecuritycredentials](https://cloud.githubusercontent.com/assets/4491168/6646925/b3afe152-c986-11e4-87bf-d9c18bb46386.png)

**Comment by DavidMGross** [comment]
![applytheruleto](https://cloud.githubusercontent.com/assets/4491168/6647573/10d985f8-c98d-11e4-922b-383441108bde.png)
![createpolicy](https://cloud.githubusercontent.com/assets/4491168/6647574/10dd96ac-c98d-11e4-95a5-50f615571bbb.png)
![createyourownpolicy](https://cloud.githubusercontent.com/assets/4491168/6647575/10eed1f6-c98d-11e4-89e2-5c397980665b.png)
![iampolicyclient](https://cloud.githubusercontent.com/assets/4491168/6647576/10f10322-c98d-11e4-85c8-4c547e4fe119.png)
![lifecycle](https://cloud.githubusercontent.com/assets/4491168/6647577/10f5215a-c98d-11e4-97e5-c0f4fd58890a.png)
![managedpolicies](https://cloud.githubusercontent.com/assets/4491168/6647578/11059aa8-c98d-11e4-9d21-af065dc303d9.png)
![permanentlydelete](https://cloud.githubusercontent.com/assets/4491168/6647579/11095206-c98d-11e4-8060-74baac526b80.png)
![servicess3](https://cloud.githubusercontent.com/assets/4491168/6647580/111cac5c-c98d-11e4-856b-4ddb700c8e94.png)

**Comment by simonv3** [comment]
@DavidMGross Could you give a bit more context as to what you're trying to achieve? You shouldn't need to deal with AWS to get images working on your local server.

**Comment by simonv3** [comment]
@DavidMGross OOOOOOOh. I see what's going on.

I'm going to close this issue so that it's not too confusing, but feel free to continue uploading images this way.

Thanks so much for filling out the details on how to get started with OpenFarm on MacOSX and dealing with AWS.
