### ISSUE TITLE
Footer not working on guide page

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#553]
@warpling 

![screenshot 2015-03-19 08 42 13](https://cloud.githubusercontent.com/assets/485583/6722964/df0e0234-ce13-11e4-8808-755716930409.png)

**Comment by warpling** [comment]
I know how to fix this, it just requires retooling how some of the vertical centering on the home page works. Should be a good time to move away from super-backwards-compatible tables towards flexbox with some graceful degradation.

**Comment by simonv3** [comment]
Do you have time to do so in the next week or so? Or is rake db:setup blocking this?

**Comment by warpling** [comment]
I’m going to try to fix it tomorrow, but I’m flying semi-blind with the db issues. That said I think it’s doable.


~Ryan

**Comment by warpling** [comment]
I think this got fixed. Can someone confirm?

**Comment by roryaronson** [comment]
Looks fixed to me :)

**Comment by simonv3** [comment]
Yep https://openfarm.cc/en/guides/jojis-cherry-tomatoes
