### ISSUE TITLE
Rename 'user' to 'member'

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#554]
I don't think the underlying models need to be changed, just wherever we use the word "user", we should use the word "member".

Example: "Become a member" vs "sign up"

**Comment by roryaronson** [comment]
I think this is a great idea for several reasons:
* It makes signing up for OpenFarm cool and have purpose/specialness. I'm now a member!
* It reinforces OpenFarm's community focus. We're like a social club, where people interact and share and have fun, and everyone is invited to join
* It opens us up to a cool revenue stream idea: membership dues. We could have an annual 'membership drive' where we ask for a sliding scale donation. Asking for a donation in this context sounds more appealing (at least to me) than let's say how Wikipedia does it with just a big banner.
* It promotes a sense of ownership in OpenFarm/the commons from our members

**Comment by roryaronson** [comment]
The word 'user' also doesn't imply 'giver' in any capacity. And we definitely want to foster the giving and sharing of knowledge!
