### ISSUE TITLE
Add Vegetative Propogation Life Stage

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#557]
One can propogate by sowing seeds or by vegetative propagation (cuttings, roots, bulbs)

**Comment by roryaronson** [comment]
After more discussion we think the better move is to add a Vegetative Propogation stage in addition to the Sow stage, rather than lumping the two together into a generic 'Propogation' stage.

**Comment by simonv3** [comment]
Do we have artwork for it?

**Comment by roryaronson** [comment]
No, but I'll ask Claire if she can make an icon right now!

**Comment by simonv3** [comment]
Cool, once we have an icon we can add this through the admin fairly easily. 

In fact, we should probably reference the image artwork through the model, instead of relying that they have the same name. Probably more managable in the long run.

**Comment by simonv3** [comment]
So, for the "Growing" and "Harvest" life stages we I just repurposed an existing image from another stage. Any images that would work for that?

**Comment by roryaronson** [comment]
Not yet. Never got one from Claire. I'll be seeing her in January, maybe I can squeeze one out of her then! Let's close this for now

**Comment by simonv3** [comment]
@roryaronson do you know if we have the assets for the others? the original illustrator or photoshop files?

**Comment by roryaronson** [comment]
We just have pngs and svgs, though I just messaged Claire asking her to add the source files to this folder: https://drive.google.com/folder/d/0B-wExYzQcnp3NVFudVFIeWRVdFk/edit

**Comment by simonv3** [comment]
:+1:

**Comment by roryaronson** [comment]
@simonv3 Here is the illustrator file: https://drive.google.com/file/d/0Bzm0yyP7JMLibFJOMV9VeXdVaGc/view

**Comment by simonv3** [comment]
That reminds me, should we be adding all of these designs and such into the repo? Instead of google drive? Or some other, a bit more public accessible host?
