### ISSUE TITLE
Add 'Transplant' Action

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#560]

**Comment by roryaronson** [comment]
And these Actions:
* 'Other'
* 'Purchase or Borrow' (product/tool)

**Comment by roryaronson** [comment]
And:
* 'Regulate Temperature'
* 'Regulate Humidity'
* 'Regulate Ventilation'

**Comment by roryaronson** [comment]
And:
* 'Move'

**Comment by simonv3** [comment]
@roryaronson, you can add these in the admin:

https://openfarm.cc/admin/stage_action_option

I can do it down the line, but I just thought I'd share in case you didn't know.

**Comment by roryaronson** [comment]
Oh, cool! Yea I'll add them then

**Comment by roryaronson** [comment]
Adding them here, does that still allow for them to be translated?

**Comment by simonv3** [comment]
They were never able to be translated through that. Hmmm.
