### ISSUE TITLE
Add 'Indirect Light' option

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#561]
that accompanies full sun, partial sun, shade, etc.

**Comment by simonv3** [comment]
I'm going to add a model for these. We should be storing all of them in the database anyway. It can be fairly flexible.

**Comment by simonv3** [comment]
Cool, model added on staging. I've got another PR on the block which should automatically generate these from what's in the database, that way you can manage them in admin as well. #562

**Comment by simonv3** [comment]
You can now manage these on live at: /admin/detail_option, I've created some basic ones to show how it's done. Note that the category is lowercase, and if you want it to show up in the "light" one it should match "light". Same for "environment", "practices", and "soil".

**Comment by roryaronson** [comment]
Awesome! I'll add some stuff now.
