### ISSUE TITLE
Guide page tooltips!

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#57]
For the following elements:
* Guide rating: "4.1 out of 5 stars from 37 reviews"
* Compatibility elements: "60% match because ____"
* Timeline vertical bar for today: "Today is Feb 21"
* Timeline horizontal bars of time: "95 days"
* Timeline vertical bars for major events such as last Spring frost: "Estimated last Spring frost: Mar 14"
* Growing Instructions unit conversions
* Growing instructions bar graph value: "Water 14 Liters/Plant, every day"

**Comment by simonv3** [comment]
This exists for compatibility elements, I'm adding timeline functionality to each crop.

**Comment by growdigital** [comment]
There's a very nice CSS-only tooltips tutorial I saw recently, will dig it out

**Comment by roryaronson** [comment]
@simonv3, there is a slight delay for the tooltip disappearing when I mouse-off of an element. This causes multiple tooltips to be rendered when moving quickly over the section.

**Comment by simonv3** [comment]
blame foundation :/ I'll have a look. These might need to be fully
redesigned anyway because we'll probably include more than just text in
them right?

**Comment by roryaronson** [comment]
Umm maybe? I hadn't thought about what else might be in them. Like, images or buttons? I would definitely think 'Learn more' links would be nice.

**Comment by simonv3** [comment]
Yeah, and link information wouldn't work at the moment.

**Comment by warpling** [comment]
It would be good to update the strings as well to say something like **Low Compatibility:** instead of just **Low** before the explanation.

**Comment by simonv3** [comment]
Thanks to @growdigital: http://www.menucool.com/tooltip/css-tooltip

**Comment by roryaronson** [comment]
I'm gonna close this one. We can switch to those non-Foundation tooltips when we have a need for em!

**Comment by simonv3** [comment]
agreed!
