### ISSUE TITLE
Raw Hashes Being Shown

### ISSUE THREAD

**Issue by MarceloAlves** [openfarmcc/OpenFarm#583]
On some pages ([like this one](https://www.openfarm.cc/en/crops/mapacho)) the raw hash values are being shown.

![Example](http://i.imgur.com/gf5fosL.png)

**Comment by simonv3** [comment]
@MarceloAlves thanks for the report! That's actually been fixed in #577, it just hasn't made its way to the production server yet (it's on staging if you want to check it out staging.openfarm.cc)
