### ISSUE TITLE
trouble for new member on initial "Your First Garden" screen

### ISSUE THREAD

**Issue by DavidMGross** [openfarmcc/OpenFarm#587]
I'm a newly-registered member, setting up my account. I get to the "Your First Garden" screen and get stuck. I set the parameters of my garden as I want them, but then it's unclear whether I should click "Save Garden" or "Create New Garden."  I try "Save Garden," which seems to work, but doesn't take me to a new page. I'm just stalled. So I think maybe I need to "give my garden a name" so I enter a name and click "Create New Garden" but that just adds another garden to the list (actually, it adds it twice, but that's another bug...).

I think there should be a clearer indication that the member has done what needs to be done to set up a garden, and an indication of what the member's next steps should be.

(issue found while using Chrome/Linux... + a variety of ad-, tracker-, and popup-blockers)

**Comment by simonv3** [comment]
Hey @DavidMGross, thanks for telling us. That's good to know. I can see why it might be confusing to set up your own garden. Do you think it would help if when you were editing your garden, it would be clearer that you were in some form of "Edit" mode? A different color background or something like that?

The new garden page section should probably be indicated better, and could use some love.

**Comment by DavidMGross** [comment]
There are three things that I think could use improvement:
 1. As a new member, the system takes you down a well-lit wizard-like path for a couple of pages, but then seems to kind of abandon you at the new garden page without any indication that the wizard has left you to your own devices. Some sort of "congratulations on finishing the process of establishing your first garden; here are some steps you can take next..." screen might mark the transition better.
 2. There is an ambiguity between "Save Garden" and "Create New Garden" as to which one you should click when you've filled out the info on your new garden. There isn't much feedback when you click "Save Garden," so the member may suspect that it was ineffective or the wrong choice.
 3. There was some sort of bug where when I clicked "Create New Garden" it created *two* new gardens with the same name.

**Comment by warpling** [comment]
Thanks for taking the time to write this out @DavidMGross! Great feedback.

On the button thing, @simonv3 (and David) What do you think of making the button language a little more sentence like: "Save This Garden", "Create A New Garden" …maybe it's a bit inconsistent with out existing buttons, but I think it clears up the ambiguity.

**Comment by roryaronson** [comment]
I have some ideas for how this can be improved as it relates to the (in-progress) member profile pages. I'll make some mockups tonight

**Comment by simonv3** [comment]
that’d be awesome, thanks Rory


—

**Comment by roryaronson** [comment]
Ok, sorry this is a week late! Forgot to post it here. [This is a mockup](https://docs.google.com/drawings/d/1a7pj7t84jdYO5le1wyYnRmw_H5CEUnjtLejKj1iUb8E/edit?usp=sharing) for how the member signup flow can be improved and also updated to work with the upcoming member profile pages (#591)

**Comment by simonv3** [comment]
This has been implemented!
