### ISSUE TITLE
Guide without a user on staging.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#596]
```
An ActionView::Template::Error occurred in crop_searches#search:

  undefined method `display_name’ for nil:NilClass
  app/views/guides/_guide_result.html.erb:6:in `block in _app_views_guides__guide_result_html_erb___1642834584179270388_70285328275500’
```

This should be easily fixed, but I'm wondering why this happened, unless someone created a guide on staging and deleted their account. If not, this means somehow a guide was created without attaching a user.

**Comment by simonv3** [comment]
The guide has a location of St. Luis Obispo, which narrows down the culprits a bit :stuck_out_tongue:

**Comment by roryaronson** [comment]
Lol, my bad. Now that accounts need email verification, I was deleting my extra ones from Rails Admin so that I could go through the sign up flow again for testing.

**Comment by simonv3** [comment]
It's cool! It was actually a good test of what happens when you delete a user. I guess it doesn't cascade to delete guides, which I'm glad we don't have to hack that functionality to make users leaving and not deleting guides. Though it'd be interesting to see if guides remain if the user goes through the delete button.
