### ISSUE TITLE
Binomial names and the endless complexity of categorizing life

### ISSUE THREAD

**Issue by andru** [openfarmcc/OpenFarm#60]
I thought I'd share what I learned while researching naming conventions for Practical Plants.

A binomial is composed of the genus name and species epithet: e.g. _Brassica oleracea_ (binomials should always appear in a contrasting style to the surrounding text, most commonly italics). This is not enough information to refer to the majority of cultivated plants, since there are almost always numerous varieties, sometimes representing very different plants with entirely different needs.  For example, the single _Brassica oleracea_ species represents the thousands of cultivars of Cabbages, Broccolis, Kales, Coliflowers, Brussel Sprouts and so on. Advice and data for one species can be entirely irrelevant for another.

There are several systems of sub-species categorization used for plants, used often interchangably, and equally often incorrectly. Browsing plant data online you'll often see epithets like _var. convar. ssp._ etc.

In my research I found the following is generally seen as 'correct': use _var._ when referring to a naturally occurring species variety. There are some cases when one should use _ssp._ (subspecies) for some subtle botanical distinction which I don't remember.  Most relevant for Open Farm is _[ICNCP](https://en.wikipedia.org/wiki/International_Code_of_Nomenclature_for_Cultivated_Plants)_ which should be used when referring to a registered cultivated variety. It also provides a means to refer to cultivars which share characteristics as a group, which is crucial.

E.g. Cabbages are a member of the Capitata group  **_Brassica oleracea_ Capitata Group**, and Brocolli are grouped as Italica **_Brassica oleracea_ Italica Group**. 

and one may refer to one of my favourite winter cabbages,  __January King__ by any of the following:
- _Brassica oleracea_ 'January King'
- _Brassica oleracea_ (Capitata Group) 'January King'
- Cabbage 'January King'

The cultivar name must always be enclosed in single quotes, and capitalised. The group must be enclosed in brackets if present, but it is not required, and should be capitalised. The last example is informal and useless for categorization.

On the opposite end of the scale, it is not uncommon for a plant common name to actually refer to an entire genus of plants made up of many very similar species with the same requirements and care conditions, and so the binomial is actually too specific.

Accordingly, I recommend a subset of these properties exist in order to categorize which plant a guide belongs, the only mandatory entry being _taxonomic rank_ and _genus_:

- taxonomic rank (genus, species, subspecies, variety, cultivar group, cultivar)
- genus
- species
- cultivar group (optional even when cultivar name is set)
- cultivar name
- subspecies
- variety

Since common names are so variable, not just from language to language but between regions, I think these are best represented as their own document rather than attached to a guide. That way a user can search by the common name they know and find all relevant guides. It would also allow the guide author to simply enter the common name they know and, if it has already been entered by someone, the remaining taxonomic information could  be auto-filled.

**Comment by simonv3** [comment]
With the common names being workable on staging, I'll mark this as closed. Basically we have all crops categorized by binomial name, and each crop has common names associated with it. Down the line we can probably add further parsing to all of these crops to let people be able to search them by the sub groups.
