### ISSUE TITLE
Choose Crop is broken on Guide Creation

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#608]
It either doesn't do anything when I type something in (which then prevents me from advancing to the next step of Guide Creation) Or it just sits there loading forever :(

We may want to rethink how that all works. If the Crop doesn't exist, should we just auto create one behind the scenes with whatever name the member types in?

![capture](https://cloud.githubusercontent.com/assets/5524043/7383397/84637c94-edd3-11e4-81f7-acef2d9ac95e.JPG)

**Comment by simonv3** [comment]
If we were to auto-create it, how do we catch typos? 

Weird that it doesn't work though.

**Comment by roryaronson** [comment]
We don't? Anyone could edit the Crop later if they found an error...

**Comment by simonv3** [comment]
But they can't merge crops yet (another feature?) so if they mistype Tomato (tomato, tomatos, tomatoes), and nothing comes up, and they continue, and we create the crop, we'll have all these duplicate crops in the database.

Maybe we should do something like "did you mean <crop name>" if they don't select something, and then if they don't choose that only then auto create?

**Comment by roryaronson** [comment]
Can't the type-ahead account for mispellings? Maybe we just show a little
message if nothing comes up: "That Crop doesn't exist in our database yet.
Did you type it correctly? If you continue, this will create a new Crop."
And then change the 'next button' to 'Create new Crop and continue'

**Comment by simonv3** [comment]
That would work!

**Comment by simonv3** [comment]
This is fixed on staging. I'm going to open another issue #618
