### ISSUE TITLE
Allow Image Upload During "Add New Crop" 

### ISSUE THREAD

**Issue by xbertolerox** [openfarmcc/OpenFarm#609]
I shouldn't have to exit the Add New Crop screen and then select Edit Crop button in order to add an image of the crop. 

![screen shot 2015-04-28 at 7 55 30 pm](https://cloud.githubusercontent.com/assets/10620877/7384121/fac1f4bc-ede0-11e4-9553-3cdced887a4c.png)

**Comment by roryaronson** [comment]
On this note, I think the Edit Crop and Add Crop pages should look identical.

**Comment by simonv3** [comment]
This is done but it's delayed job. Which is weird. It makes the whole process faster, but then looks like it didn't work once something is updated. @RickCarlino, any thoughts on that?
