### ISSUE TITLE
Can't Delete Images

### ISSUE THREAD

**Issue by xbertolerox** [openfarmcc/OpenFarm#610]
I can't delete the image I've uploaded to my guide, and I couldn't delete an image I uploaded to the crops. 
![screen shot 2015-04-28 at 8 17 45 pm](https://cloud.githubusercontent.com/assets/10620877/7384243/c73e450c-ede3-11e4-8445-c5d9c0e20e9e.png)

**Comment by simonv3** [comment]
Note: this is fixed on crops, still need to test it for guides.

**Comment by simonv3** [comment]
Status of this right now

* [ ] Images get upload correctly.
* [ ] Featured images get removed correctly.
* [ ] Previously uploaded stage images don't show on edit guide.
* [ ] Action images doesn't work at all (can't upload, can't do nothing).

**Comment by simonv3** [comment]
This would be fixed by #695.
