### ISSUE TITLE
Add "Years" to Stage Duration

### ISSUE THREAD

**Issue by xbertolerox** [openfarmcc/OpenFarm#611]
For an apple tree it takes about 3 years to reach maturity. If we prefer going the 36 months route then disregard. 
![screen shot 2015-04-28 at 8 49 02 pm](https://cloud.githubusercontent.com/assets/10620877/7384443/14b8a116-ede8-11e4-9876-e147915548de.png)

**Comment by simonv3** [comment]
This is a conversation that I don't think has reached a satisfying conclusion: 

https://github.com/openfarmcc/OpenFarm/issues/411
https://github.com/openfarmcc/OpenFarm/issues/505

(and probably some other places I couldn't immediately find)
