### ISSUE TITLE
Add to garden dropdown borked if you don't have any gardens

### ISSUE THREAD

**Issue by emily-plummer** [openfarmcc/OpenFarm#612]
![image](https://cloud.githubusercontent.com/assets/8960591/7384646/20a1f776-edec-11e4-9171-c5d4ca4a531a.png)

Maybe we should add: 'You haven't created any gardens yet, create one now!' in the area

**Comment by simonv3** [comment]
Yep!

Also, note, that it takes some time for gardens to finish loading, which is also a bug.

**Comment by warpling** [comment]
Add something cute to it Emily!


~Ryan

**Comment by emily-plummer** [comment]
probably I'll just add this

![kittengif](https://cloud.githubusercontent.com/assets/8960591/7397023/6c8535fe-ee5a-11e4-9d3a-f7233adb82f0.gif)

**Comment by simonv3** [comment]
This is now fixed in #661!
