### ISSUE TITLE
Footer should be on a single line (On Desktop)

### ISSUE THREAD

**Issue by xbertolerox** [openfarmcc/OpenFarm#620]
*Edit by Simon:* Have a look at [this comment](https://github.com/openfarmcc/OpenFarm/issues/620#issuecomment-118980611) for newcomer instructions on how to fix this!

![screen shot 2015-05-06 at 10 26 24 am](https://cloud.githubusercontent.com/assets/10620877/7499172/ba36d7d2-f3da-11e4-9283-ace4d06908c5.png)

**Comment by warpling** [comment]
Why do you think it’s bad to span two?

Is it because the two rows are close together?

**Comment by xbertolerox** [comment]
I'm not used to seeing such large footers, and if the content/links can fit
on one line, then they should be put on one line. Just my gut reaction
though, and it may be that I liked the old footer and remembered how it
looked.

On Wed, May 6, 2015 at 10:32 AM, Ryan McLeod <notifications@github.com>
wrote:

> Why do you think it’s bad to span two?
>
> Is it because the two rows are close together?
>
> On Wed, May 6, 2015 at 10:29 AM, xbertolerox <notifications@github.com>
> wrote:
>
> > ![screen shot 2015-05-06 at 10 26 24 am](
> https://cloud.githubusercontent.com/assets/10620877/7499172/ba36d7d2-f3da-11e4-9283-ace4d06908c5.png
> )
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/openfarmcc/OpenFarm/issues/620
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/620#issuecomment-99545380>.
>



-- 
Kevin Bertolero
Forestry & Natural Resource Management, Cal Poly
(209) 312-1075

**Comment by warpling** [comment]
What do you think makes it feel large? The double-decker-ness or the font-weight or something else? I’ve seen quite a few fat footers, but agree it can look a little out of place, so we should figure out how to make it stand-back maybe?(It could span the whole width on large screens, it’s just hard-ish to know when it’ll all fit and avoid having 5 items on one line and 1 on the next)


~Ryan

**Comment by xbertolerox** [comment]
It's the double-deckerness. It just looks odd to stack them when they can
clearly all fit.

On Wed, May 6, 2015 at 10:44 AM, Ryan McLeod <notifications@github.com>
wrote:

> What do you think makes it feel large? The double-decker-ness or the
> font-weight or something else? I’ve seen quite a few fat footers, but agree
> it can look a little out of place, so we should figure out how to make it
> stand-back maybe?(It could span the whole width on large screens, it’s just
> hard-ish to know when it’ll all fit and avoid having 5 items on one line
> and 1 on the next)
>
>
> ~Ryan
>
> On Wed, May 6, 2015 at 10:37 AM, xbertolerox <notifications@github.com>
> wrote:
>
> > I'm not used to seeing such large footers, and if the content/links can
> fit
> > on one line, then they should be put on one line. Just my gut reaction
> > though, and it may be that I liked the old footer and remembered how it
> > looked.
> > On Wed, May 6, 2015 at 10:32 AM, Ryan McLeod <notifications@github.com>
> > wrote:
> >> Why do you think it’s bad to span two?
> >>
> >> Is it because the two rows are close together?
> >>
> >> On Wed, May 6, 2015 at 10:29 AM, xbertolerox <notifications@github.com>
> >> wrote:
> >>
> >> > ![screen shot 2015-05-06 at 10 26 24 am](
> >>
> https://cloud.githubusercontent.com/assets/10620877/7499172/ba36d7d2-f3da-11e4-9283-ace4d06908c5.png
> >> )
> >> > ---
> >> > Reply to this email directly or view it on GitHub:
> >> > https://github.com/openfarmcc/OpenFarm/issues/620
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/openfarmcc/OpenFarm/issues/620#issuecomment-99545380>.
> >>
> > --
> > Kevin Bertolero
> > Forestry & Natural Resource Management, Cal Poly
> > (209) 312-1075
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/openfarmcc/OpenFarm/issues/620#issuecomment-99546649
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/620#issuecomment-99550074>.
>



-- 
Kevin Bertolero
Forestry & Natural Resource Management, Cal Poly
(209) 312-1075

**Comment by roryaronson** [comment]
I thought this looked weird too. After looking at it again today, it is the center aligned-ness that looks weird to me when there is more than one line.

I think putting all the links on one line with sufficient padding in between and center-justifying *the whole* line would look best. Then the links can wrap to another line as needed while staying centered.

**Comment by simonv3** [comment]
This is perfect for a newcomer!

1. Find the `footer.html.erb` file
2. Change the Foundation column classes. 12 / 6 footer items is 2, so you would just change `small-4` to `small-2`. 
3. Done! 

Let us know if you need any help getting started on this!

**Comment by simonv3** [comment]
Note: the footer is also semi-broken on small screens. It should probably all fall into a vertical list.
