### ISSUE TITLE
Email confirmation link should go to member profile page

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#628]
Right now it goes to the intermediate 'Thanks for joining! Now just a few more things.' page which (with the new signup flow) I have already filled out all that info.

*Edit by Simon:* I've added a short guide on how to solve this problem: https://github.com/openfarmcc/OpenFarm/issues/628#issuecomment-118979989

**Comment by simonv3** [comment]
What if someone hasn't though?

**Comment by roryaronson** [comment]
Hmmm good point. I guess that would be the case if the member pressed 'do this later' or if they immediately went and checked their email after seeing the alert.

Is there a way to put some locgic in whereby a member who has already entered in that info is sent to the member profile page?

Also, on a side note, is there a way yo

**Comment by roryaronson** [comment]
Oops, as I was saying:

On a related side note, is there a way to delay the 'you need to confirm your account' alert for that intermediate page and the first time they get to the member profile page to enter their favorite crop? It was kind of disruptive/distracting I thought.

**Comment by simonv3** [comment]
This would be a good one for newcomers!

1. Have a look at the confirmations controller where this all happens `confirmations_controller.rb`
2. Check that a user who has filled in the right information (bare minimum: location, everything else has default false). 
3. If the user doesn't have the right information, forward to finish, if they do, send them to show. Look at line 17.
4. Write some tests for this. Look at `user_session_spec.rb` for related user session specs.

Let us know if you are thinking of tackling this problem and want any help!

**Comment by lizschwab** [comment]
I'm taking a look at this one. What url does the confirmation link point to?

**Comment by simonv3** [comment]
Hey @lizschwab! Thanks for taking this on :) 

I think it's this: https://openfarm.cc/users/confirmation?confirmation_token=<token>

I can't remember exactly, but this is probably a default set by [Devise](https://github.com/plataformatec/devise)

**Comment by TanSA05** [comment]
Hi, @simonv3!
I had a discussion with my coaches this morning, and I'm planning on doing the following to reolve this issue:
- Use a custom method that checks for location in `user.rb`
- Add 3 conditions to `confirmations_controller.rb` which will be:
    - No errors (if true, will redirect to show)
    - Missing location in user details (if true, will redirect to action: finish)
    - Some other error (currently the else condition) which remains same

Let me know if this is okay, so that I can proceed to writing the code?

**Comment by simonv3** [comment]
In general this looks good to me. I wish there was a bit of a better way to detect whether this has been filled in rather than just the location. Maybe, but not as part of this ticket, we need to have an invisible toggle that gets set when the user submits this form?

`User.has_filled_in_account_details = <boolean>`

**Comment by TanSA05** [comment]
I took the location because you'd mentioned it previously. I can add others too in this particular method only, like the `user_setting.units` details

**Comment by simonv3** [comment]
Yeah, I know, I don't think there's a foolproof method to detect whether someone's filled this in. But units is probably a good one to check as well. I say go for those two, and in the future we can think about doing a hidden boolean to check against this.

**Comment by TanSA05** [comment]
Okay, great! I'll get to the code part now, then! :)

**Comment by simonv3** [comment]
Thanks so much!

**Comment by TanSA05** [comment]
@roryaronson @simonv3 This issue is fixed! :dancer:

**Comment by simonv3** [comment]
Yeaaa!

**Comment by roryaronson** [comment]
Woo!

On Sat, Jul 9, 2016 at 1:33 AM Simon <notifications@github.com> wrote:

> Yeaaa!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/628#issuecomment-231523255>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFRKS5hR7UKDOTyb_7TQF65weRGK6Rn0ks5qT1zCgaJpZM4ETPNW>
> .
>
-- 
- Rory
