### ISSUE TITLE
Action photo uploads bug

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#631]
I'm making a guide. While waiting for a photo to upload to an Action, I switched to another Action so I could start filling out the info. The image spinner and progress bar showed up there too (even though the photo was for the first Action). It shouldn't show up there.

**Comment by roryaronson** [comment]
Okay, this is more than a visual bug. I was just filling out an Action while I had a photo uploading to a different Action. Once the photo finished uploading, it was applied to the Action I was currently editing (the wrong one)

**Comment by simonv3** [comment]
Yeah that's because there's a "currently editing action" I think. I'll have to have a think about this.

**Comment by roryaronson** [comment]
:BOOM:

On Thu, Dec 10, 2015 at 6:43 PM Simon <notifications@github.com> wrote:

> Closed #631 <https://github.com/openfarmcc/OpenFarm/issues/631>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/631#event-488926981>.
>
-- 
Rory Aronson
