### ISSUE TITLE
Drag and Drop photo uploads

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#632]
Would be nice if I could drag and drop photos into the green upload box

**Comment by simonv3** [comment]
Can't you?

**Comment by roryaronson** [comment]
Nope. At least not in the latest Chrome on Windows or Chrome on Chrome OS.

**Comment by simonv3** [comment]
It's probably worth looking at something like this https://github.com/danialfarid/ng-file-upload for inspiration, or just stealing parts of it, to make it work alongside our uploading scripts.

**Comment by simonv3** [comment]
Okay, this was actually a bug in how the previous image uploader was set up. Should now be fixed, but not yet with visible feedback.

**Comment by roryaronson** [comment]
Yep just tested it on staging :)
