### ISSUE TITLE
Guide not saving properly if there are Actions

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#634]
I just finished making my Guide, went to go click Publish, and then it just sat there spinning for a long time. It never stopped. :( I opened up a new tab to OpenFarm and got an alert 'You just published a Guide!'. Huh. I went to my Guides, and sure enough it was there. Clicked it, but the only info that saved was the main image and the overview. None of my life stages, no other photos, nothing even that gave me compatibility scoring.

I pressed Edit Guide and then copied and pasted some info from my original tab (that was still spinning) and tried to save it in the new tab. It just started spinning again. I closed this second tab.

I then opened it again and tried to edit again. This time I just added life stage info (sun amount, location) and saved it. That worked.

Then I edited again and tried to add some text for one Action. Saving failed. So it has to do with the Actions info.

My guide: https://openfarm.cc/en/guides/555273e264633900031c0000

**Comment by roryaronson** [comment]
From my console:

``` TypeError: Cannot read property 'filter' of undefined
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:21:27196
    at Array.map (native)
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:21:27142
    at Array.forEach (native)
    at t.sendStages (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:21:26617)
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:17:32487
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:27083
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:5:7563
    at c.$eval (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:5:14507)
    at c.$digest (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:5:13056)(anonymous function) @ application-aca79496e6ca574a833bf1523ba469ec.js:5 ```

**Comment by simonv3** [comment]
Fixed by @dedesite :)
