### ISSUE TITLE
Crop typeahead suggestions are buggy and inconsistent

### ISSUE THREAD

**Issue by andru** [openfarmcc/OpenFarm#636]
This is on staging. It could just be that some search index isn't being built because staging, but it might be a bug so here's a recording:

https://drive.google.com/file/d/0BxUOw4ZqnwS8RENNSEhremk3ZDQ/view?usp=sharing

* The same string can return totally different entries (I enter `straw` a few times, with different results).
* The string `straw` matches `straggly gooseberry` as the no.1 match
* The string `strawberry` doesn't match a load of plants with that exact substring 
* `strawberry wtf fooo reeaaal` matches plenty of strawberry related things, however

**Comment by roryaronson** [comment]
Yea this is also buggy on production. It always has been :(

Makes a somewhat poor first impression for anyone on the homepage looking for something...

**Comment by simonv3** [comment]
@roryaronson this doesn't even seem to work on production at all (nothing comes up). I've just made a lot of bug fixes so I'm going to roll out what's on master now, see if that fixes this due to indexing.

**Comment by simonv3** [comment]
So it's also happening on production, but there's an interesting twist:
1. I type in `Waterlily` and completely gibberish results return.
2. I delete waterlily and type in something else (`hello`), and results for waterlily show up.

**Comment by simonv3** [comment]
I'm going to proclaim this fixed in #661.

**Comment by roryaronson** [comment]
Huzzah!!
