### ISSUE TITLE
Guide deletion policies

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#637]
Andru has brought up a good point: why should members be able to delete their guides?

I always thought of it as a way for members to remove their garbage guides. Like, if they are just playing around and then realize that their test/fake guide is now stuck on their account and in search results when it has no real information. The issue arises though if a guide is being used by others, then deleted by the creator.

We want to empower members to fix their mistakes, while not giving them too much power such that they can revoke/delete useful content.

I propose this policy idea: Guides can only be deleted if no member has added it to their garden or commented on it (when commenting is a thing)

An alternative idea: Guides can only be deleted if they are less than 1 week old

**Comment by simonv3** [comment]
Yeah, I always saw guides as being semi-permanent, so I'm on board with not making them delete-able. 

However, if you make them lock in after a week, how do you phrase that so that it doesn't come off as completely totalitarian?

**Comment by simonv3** [comment]
This is related: 596 (basically deleting an account leaves guides, which is a bug at the moment - though fixed on staging).

**Comment by roryaronson** [comment]
We could also have a 'request to be removed' button on every Guide. That's going to have to exist anyways for members to flag inappropriate Guides. Then a community moderator can approve or deny the request based on if it really is an empty/test/inappropriate guide or not.

**Comment by sophiakc** [comment]
@roryaronson is this discussion still pending?

**Comment by roryaronson** [comment]
Yes, considering that empty guides will probably remain as drafts now we can probably close this discussion. I think we'll need to revisit it when we get to a point where we need a "Flag as Inappropriate" button and policies for when to remove content, but that's probably a ways off.
