### ISSUE TITLE
OpenFarm Mascot?

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#639]
I think a mascot could help liven up OpenFarm. The mascot could be a unifying element seen throughout the site and on our promotional materials, and a fun way to engage members in our 'teaching moments'. Ex: when someone is creating a Guide, the help text for each section could be coming from the mascot.

No, I'm not talking about some heinous [windows paperclip](http://2.bp.blogspot.com/_HKjlXpb-k1I/SZhf3TEuh9I/AAAAAAAAGRI/U-CixLyv-QA/s1600-h/paperclip.jpg) - but something tasteful, relateable, symbolic, and done thoughtfully.

What do you think?

**Comment by warpling** [comment]
I like the idea :)

I was trying to find a picture of the clips they use to attach orchids to sticks but couldn’t find any :P

**Comment by xbertolerox** [comment]
I love the idea of a Bee as our mascot. A friend of plants and farmers, the bee is social and relatable. We can also highlight the plight of the bee. Plus buzz lines - - - - - - - - - - -

**Comment by warpling** [comment]
Bee++

~Ryan

**Comment by xbertolerox** [comment]
![picture13397986852821](https://cloud.githubusercontent.com/assets/10620877/7647907/ada82e3c-fa90-11e4-9bbb-f04a32eca70e.jpg)

**Comment by xbertolerox** [comment]
![images](https://cloud.githubusercontent.com/assets/10620877/7647918/cb439abc-fa90-11e4-9a40-7f9e68d36e78.jpeg)

**Comment by roryaronson** [comment]
I like the bee idea too, and we already talked about it a bit on Slack back in January but didn't really make an steps towards implementation. It definitely goes well thematically. I don't think I would be a fan of any vegetable or other plant mascot. Plants with faces are [pretty creepy](https://bycommonconsent.files.wordpress.com/2010/12/images.jpg), plus we don't want to eat our mascot! ;p

I like the bee in the style of a botanical illustration. Here is a friend's bee company banner that I really like:
![251993_326395877437773_325102099_n](https://cloud.githubusercontent.com/assets/5524043/7663547/e5900398-fb20-11e4-8a23-29c1742dfdb5.jpg)

Anyways, sounds like we might be all on a board (looking at the Slack convo again now)

**Comment by simonv3** [comment]
How about we create a job listing for this on the [open source design job board](http://opensourcedesign.net/jobs/)?

**Comment by roryaronson** [comment]
That sounds like a good idea! I have yet to figure out our financial situation to see how much money we still have. Will report back

**Comment by simonv3** [comment]
I actually ended up posting it, it's listed as gratis, http://opensourcedesign.net/jobs/jobs/2015-07-10-design-openfarm-mascot---openfarm.html, but we can change that fairly easily :)

**Comment by roryaronson** [comment]
:+1:

**Comment by elioqoshi** [comment]
Hey guys, I might be able to take this over. I have done the mascot for Glucosio (www.glucosio.org ) before: https://dribbble.com/shots/2252597-Glucosio-Mascot-Glucat-White-Background

**Comment by roryaronson** [comment]
@elioqoshi that would be awesome, thanks for offering your help! I see you've done a handful of graphics for other open source projects too :)

Would you like to throw together a few concepts and share them here?

Also, for more real-time communication we could talk in the Slack group.

Thanks

**Comment by warpling** [comment]
🐝‼️👍

**Comment by simonv3** [comment]
Hey @elioqoshi, welcome to the OF community - it's great to see you here :)

Love to see what you come up with. We've also got some other icon design ideas if you're interested.

**Comment by elioqoshi** [comment]
Hey guys! This will most likely get my attention near December, as I'm caught up with stuff now (US Visa and some other stuff). However I will write an article on SitePoint.com too where I will cover OpenFarm and make a call for designers to contribute.

However you can count on my help with the mascot, it's just that I will need a bit of time with that :)

**Comment by roryaronson** [comment]
Sounds good Elio, thanks for the heads up and the shoutout on sitepoint :)

On Mon, Nov 16, 2015, 4:04 PM Elio Qoshi <notifications@github.com> wrote:

> Hey guys! This will most likely get my attention near December, as I'm
> caught up with stuff now (US Visa and some other stuff). However I will
> write an article on SitePoint.com too where I will cover OpenFarm and make
> a call for designers to contribute.
>
> However you can count on my help with the mascot, it's just that I will
> need a bit of time with that :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/639#issuecomment-157213958>
> .
>
-- 
Rory Aronson

**Comment by sbchittenden** [comment]
![openfarm_logo](https://cloud.githubusercontent.com/assets/10438537/13084219/cb4fdf2c-d495-11e5-86ba-309899923c6a.png)
Hi OpenFarmers! -  I saw the post on Open Source Design and thought I would submit an idea. :)

**Comment by sbchittenden** [comment]
![openfarm_logo_2](https://cloud.githubusercontent.com/assets/10438537/13087053/49e59a5e-d4a3-11e5-9727-c51aaa398f28.png)

Another idea.  This one is more in the mascot vein. :)

**Comment by warpling** [comment]
Oo very nice!! :smiley: I do feel the tiniest bit intimidated by the bee currently—maybe it's the stripes or teeth? Perhaps it could go a slightly more bumble-bee direction with some short dangling legs for friendliness sake and to disambiguate from any wasp confusion? I'm a fan of this second mascot direction though!

On the typeface front, my opinion is that less playful typefaces help distinguish OpenFarm as a tool and robust community, although ones like this are fun and friendly… It's a tough balance, but I think it's the job of the mascot to soften the "brand" if I dare use that word here. :bee:

**Comment by sbchittenden** [comment]
![openfarm_logo_2_revised](https://cloud.githubusercontent.com/assets/10438537/13088317/003f5c04-d4a9-11e5-90d4-b196256ba054.png)
@warpling Thanks for the feedback, here is a softened bee with arms and a less playful font.  Let me know what you think!

**Comment by sbchittenden** [comment]
![bee openfarm](https://cloud.githubusercontent.com/assets/10438537/13089783/8e1e957a-d4af-11e5-9c30-af929fa0cd59.jpg)

Bee with the openfarm word mark from the website.

**Comment by warpling** [comment]
I think that works a lot better! Not sure what @roryaronson's thoughts on changing the logotype, but I think it works well with the current.

What are your thoughts on the teeth? I think if (s)he has them they should be whiter like the original :grimacing:? (I'm definitely not character creation expert but I tried softening the corner of the mouth a bit and I think maybe that helps the friendliness. What do you think?)

I think the legs help a lot! Thoughts on more bee like dangly/limp legs?
![image](https://cloud.githubusercontent.com/assets/220240/13090234/62590ba6-d4a9-11e5-941d-6411d0c9c6f3.png)

**Comment by warpling** [comment]
ALSO I think I figured out the wasp thing! Bumble bees (and honey bees) are mostly fuzzy yellow with black stripes; wasps tend to be more black with yellow stripes on their tail parts.
![notabee](https://cloud.githubusercontent.com/assets/220240/13090359/317a5bce-d4aa-11e5-8df2-f8f4ae68400b.gif)

**Comment by warpling** [comment]
While I was googling I found some fantastic clipart that may be a good fallback option:
![can-stock-photo_csp6194645](https://cloud.githubusercontent.com/assets/220240/13090374/42f86db4-d4aa-11e5-8a0a-1e702c67d035.jpg)

**Comment by simonv3** [comment]
yikes. 

These are some awesome first steps @sbchittenden! I think the legs do bring down the perceived "waspness" of the second mascot. What if it didn't have the pointy nose? That's something I also associate with wasps. 

The first mascot looks like I would expect it to be on a honey label. This might not be a bad thing? Maybe with more rounded stripes on the body that are a bit wider?

**Comment by sbchittenden** [comment]
@warpling @simonv3 
Thanks! I will work on incorporating those ideas and post another version soon. Unless you just want to go with the clipart fallback... :P

**Comment by sbchittenden** [comment]
![openfarm_logotype mascot](https://cloud.githubusercontent.com/assets/10438537/13099660/bd02101e-d4f1-11e5-90d2-76d0ab31011b.jpg)

Ok: more bee-like dangle legs, soft antennae, rounded mouth (went pink!?), more stripes, less wasp-y nose.

**Comment by warpling** [comment]
Oh nice! That all helps a lot!! Especially the antennae (didn't even realize that was missing). I dig the legs a lot too. Still unsure on the mouth color (I feel like it works but I'd have to look at other mascot/cartoons to know why it feels off). Now we're getting into nit pick territory and I'm not sure how easy this is to mess with but what do you think of the tail-segment (and body) maybe being less bulbous and more candy-corn/teardrop/rounded/tapered (got enough descriptors there? :P) to be more like a honey bee? Maybe realism isn't good for a mascot though. Curious to hear @roryaronson's thoughts!

**Comment by sbchittenden** [comment]
![bee_fatter](https://cloud.githubusercontent.com/assets/10438537/13117308/a0ed0f3a-d55c-11e5-8946-4437f0c52dbd.jpg)
![bee_thinner](https://cloud.githubusercontent.com/assets/10438537/13117309/a0eda83c-d55c-11e5-8fe1-4723ceeb5759.jpg)

@warpling 
Cool! Here are two modified versions (well one with just a new mouth).  The bottom version just returned from honey bee boot camp, lost some weight, improved his self image, etc.

**Comment by warpling** [comment]
Hahaha nice! Much less _plump_! I like this bee a lot.
I think that mouth with the shadow works well since I'm no longer thinking "pink teeth", I'm thinking "pink mouth" which I guess is still silly for a bee but hey :P Do you think there's anything in the stripes you could tweak to further drive home friend-bee-ness? Maybe a less uniform spacing that gets slightly closer towards the stinger could help (nothing dramatically different), or tapered bands at the edges, or just more yellow than black (sorry if I'm driving you mad with all this).

What do you think of a less pronounced stinger? Suicidal stinging with honey bees is such a sad affair. :bee::boom::skull: 

![image](https://cloud.githubusercontent.com/assets/220240/13121570/96626bd6-d567-11e5-8d01-b0918a47eb71.png)

![image](https://beespotter.org/topics/bio/Apis/Images/Apis_mellifera.jpg)

**Comment by sbchittenden** [comment]
Incorporating friend-bee feedback. Hold bees...

**Comment by sbchittenden** [comment]
![bee_thinner_mod_stripes](https://cloud.githubusercontent.com/assets/10438537/13122264/5b7c908a-d573-11e5-8ea3-6db227c9b99a.jpg)
Tweaked the stripes and after some counseling (s)he has a less aggressive/suicidal stinger.

**Comment by simonv3** [comment]
I'm really liking that last one. I was just about to suggest maybe messing with the spacing on the bee stripes, or making them wider, and I think what you just posted is definitely getting really close. I also think the mouth is great. 

Thanks so much for doing this!

One more thing: do you think you could give us a couple of scaled down options?

**Comment by sbchittenden** [comment]
@simonv3 - My pleasure, can you clarify scaled down?  Smaller bee in relation to the logotype?

**Comment by simonv3** [comment]
Yeah, I imagine that the bee would get used at different scales as well. Eg. originally it was intended to get used alongside explanatory text during guide creation. I don't think we want different shapes at this stage, but just seeing what it looks like smaller would be cool (too cluttered?) or larger (for a poster?). Looking at the bee I don't think larger will be an issue, but smaller might (eg the legs might get lost, and maybe that's okay)?

**Comment by sbchittenden** [comment]
![bee_80x80](https://cloud.githubusercontent.com/assets/10438537/13123219/7bebb9f4-d578-11e5-94c9-82bff6466830.jpg)
![bee_128x128](https://cloud.githubusercontent.com/assets/10438537/13123162/2add0b4e-d578-11e5-862c-c6ea138ca86a.jpg)
![bee_256x256](https://cloud.githubusercontent.com/assets/10438537/13123163/2addb7c4-d578-11e5-8c85-37a9f49e320c.jpg)
![bee_350x350](https://cloud.githubusercontent.com/assets/10438537/13123161/2adad7ca-d578-11e5-85bc-243b3f6446d1.jpg)

Here is the bee at approximately 80px, 128px, 256px, 350px

**Comment by jsimplicio** [comment]
I think it's looking awesome and recognizable even at that smallest size

**Comment by simonv3** [comment]
Awesome! Yeah, agreed with @jsimplicio. I think I even like it best at the smallest size :). 

I suspect @roryaronson is away somewhere, but I'm curious about what he thinks too. Would also love to hear @andru's thoughts.

**Comment by sbchittenden** [comment]
Thanks @jsimplicio and @simonv3!  I'll keep checking in for further feedback.

**Comment by warpling** [comment]
Solid! I think that helped a lot!

**Comment by edunham** [comment]
The bee is adorable! Thank you for giving it the right number of legs and wings :+1: Pedantically, though, apis mellifera (the [western honey bee](https://en.wikipedia.org/wiki/Western_honey_bee)) don't have the same stripes on their thorax (torso) as on their abdomen. When a bee's thorax looks striped, it's an optical illusion caused by the yellow hairs (possibly covered in pollen) on a black exoskeleton. 

Additionally, honey bees carry pollen in "saddle bags" on their rear pair of legs, like this: 

![bee saddlebags](http://i.imgur.com/aHzNiRf.jpg) 

It could be cute to give the mascot bee such saddlebags full of vegetables if you want to tie more into openfarm's gardening theme, though I can see how they might make the logo too busy.

**Comment by roryaronson** [comment]
I'm here! @sbchittenden thank you for leading this charge! I love what's been presented so far, and the progress that's been made so rapidly :+1: :+1: 

I'll give my feedback from the very start. The very first thing I thought of when I saw your first post was "sports team mascot". While I think its great that I though of 'mascot', the sports vibe solicited me to think of words like 'competitive', and 'friendly but macho', which are things I think we want to avoid.

The later modifications of a less pronounced stinger, softening of the mouth, slight change in form of the nose (from a distinguished point to a more integrated bulge), and the addition of the legs and antennae really help make the bee look friendlier and take away the sports vibe. The bee feels more like a friend now. Great suggestions @warpling!

I like our original typeface most and would like to see the homage to the open-source logo remain. While the more playful font suggestion is good to get out as a mockup for everyone to see, I agree with @warpling that the current choice gives me confidence that OpenFarm is a tool, resource, and a community to be taken seriously.

The second thing I think of when looking at these is [Igor](https://www.youtube.com/watch?v=nxxSIX3fmmo). Specifically, the eyes feel bulbous and don't look quite 'right', and the bee has an overall hunched posture. Both of these things make the bee seem a little too goofy/cartoony to me.

I imagine the bee being used as both a logo/mascot, as well as throughout the site to give helpful hints to OpenFarm members. Because of the second use case, I think we want to move a little towards a look of 'intelligent' and 'knowledgeable', even 'trustworthy' so that as a user of OpenFarm, I feel confident in learning and taking advice from our friend.

For the eyes, I'm not sure what specific changes would make them look more 'right', but it may be worth trying some different sizes and shapes. It would be awesome to see a bunch of iterations side by side on one image. Like, one of what we currently have, one with eyes 10% smaller, one with them 20% smaller, one with different shaped pupils, one with smaller pupils, etc.

A few versions of a de-hunched bee would be great too to see if we think that helps.

Now getting down to the most recent iterations. I think adjusting the stripes and de-plumping was a good call.

I think rounding the stinger *slightly* more would help make the bee even friendlier. Maybe like this one:

![capture](https://cloud.githubusercontent.com/assets/5524043/13130424/a00b8e70-d598-11e5-88d5-0c49125b64b9.JPG)

It might look good to remove the last yellow stripe and make the second to last yellow stripe slight thicker? I dunno, just spitballin :)

Overall, the bee is looking awesome, and thanks again for helping with this! And everyone else for chiming in with the great feedback! Woooo :smiley: :bee:

**Comment by sbchittenden** [comment]
![openfarm_bee_comp_page](https://cloud.githubusercontent.com/assets/10438537/13133952/1107d74e-d5be-11e5-9fa8-7ed9bf2bd6d1.jpg)
Hi All -  Here is a revised bee... less hunched overall and with some variations in eye size and pupil shape. I also rounded out the stinger some more and adjusted the striping a bit.  @roryaronson hopefully we are moving away from Bee-gor (sorry, last bee pun, I promise).  I numbered these for easier reference as the hive population grows.

**Comment by roryaronson** [comment]
Ooooh nice! I definitely like the less hunched bees more. I think we've successfully departed from Bee-gor :stuck_out_tongue: 

I think the simplified and rounded stinger works better too, and should increase quality at smaller scales.

As far as the eyes go, I think my favorite is 2, followed closely by and 3. Which ones do you like best?

**Comment by sbchittenden** [comment]
I agree about the stinger and do think it will read better at smaller scale.  I am also partial to 2 although 8 is nice as well.

**Comment by warpling** [comment]
Thanks for the grid @sbchittenden—super useful. Seeing these variants is really interesting… I find 5/6 to be new favorites for me although 2/3 are nice good. I think to me, the taller/narrower eyes are more cat-like and less friendly than the circle ones. there's something pleasing to me about the middle-row eye size.

**Comment by roryaronson** [comment]
Now that I look at them again, I'd say I like all of them except the ones in the left column.

Another thing to try out: The wings are pretty bright white. Maybe giving them a very slight yellow or brown tinge, combined with some subtle 'veins'? That might make it too busy, but worth trying out I think. Actually, it could be pretty cool to have the wings be semi-transparent so that whatever background is on the web page shines through bit!

![capture](https://cloud.githubusercontent.com/assets/5524043/13134519/0285541e-d5bc-11e5-81e5-61e07dcb0f0f.JPG)

**Comment by roryaronson** [comment]
On the subject of pupils, I agree with @warpling that the round pupils look a little friendlier and more bug-like. I think I like the oblong ones because it looks like the bee is opening up its eyes, or 'perking up' in some way as though its about to say something, or greet you.

**Comment by warpling** [comment]
Not sure I can agree about the wings. I think veins might bee too busy and  could take us down a bells and whistles avenue that never ends :stuck_out_tongue: The wings do look bright here, but it could just be the background and most of OF is pretty light. The transparency is a really neat idea but might prove hard to apply consistently across platforms; the opaque white almost gives a sense of motion. I'd be curious to see more bee shaped wings (or at least a larger top wing), but again, apologies if we're heading too far into a [make it pop](http://theoatmeal.com/comics/design_hell), human-microphone point.

**Comment by elioqoshi** [comment]
That's looking great! @sbchittenden 
Maybe remove 2 arms so the bee has 4 instead of 6? For simplicity purposes.

Also, I'd love to see a version without any black outlines on the shapes. The bee itself looks quite cartoonish, yet it doesn't fit very well with the wordmark which is quite minimalistic.

Great work so far!

**Comment by sbchittenden** [comment]
![brown_bee_solid_bg](https://cloud.githubusercontent.com/assets/10438537/13151659/61123440-d628-11e5-832f-a82852192ec4.jpg)
![brown_bee_wtrees](https://cloud.githubusercontent.com/assets/10438537/13151660/6112911a-d628-11e5-88e8-067f594c88c0.jpg)

Ok, so I went with middle of the pack, no.5 round eyed bee for these versions.  @elioqoshi I changed the black parts of the bee to a dark brown, which I think softens the outlined look, as well as reduced (or removed) the stroke width on the wings, and parts of the body. @warpling I did some versions with a larger top wings and also adjusted the colors to make them less bright.  Tried out some variations of wing transparency as well (over solid background as well as a perhaps *too* busy photo background...)

**Comment by andru** [comment]
These are looking amazing.
The ones without wing outlines rock my world. I think the softening from
black to brown is great, although I wonder if the head could be slightly
darker than the body. Top or middle right work the best imo.

**Comment by roryaronson** [comment]
Wow, these are really looking great! :bee: 

I agree with everything @andru said and would add that slightly darker legs might help differentiate them from the body.

I like both the larger and the original size wings. Transparent wings are doing it for me, though I'm not super attached to them because the less bright colors you chose for the other bees look very nice.

This one is my favorite:
![capture](https://cloud.githubusercontent.com/assets/5524043/13158267/0e3bb2c8-d641-11e5-9363-20a92723f437.JPG)

**Comment by warpling** [comment]
I think the brown could be slightly darker, and I dig the transparency on the wings—can't decide on outlining :)

**Comment by xbertolerox** [comment]
Wow Sam, impressive work. I'm loving all these rapidly designed iterations.

My small point of input is to vote for outlined wings, in case you put the
bee on a white background.

Cheers,
-Kevin

On Thursday, February 18, 2016, Ryan McLeod <notifications@github.com>
wrote:

> I think the brown could be slightly darker, and I dig the transparency on
> the wings—can't decide on outlining :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/639#issuecomment-185928431>
> .
>


-- 
Kevin Bertolero
Zen Laser Collective <http://www.zenlaser.co/>
Production Manager & Founder

**Comment by sbchittenden** [comment]
![revised_brown_bee_wbg](https://cloud.githubusercontent.com/assets/10438537/13165974/ef31304e-d67f-11e5-8956-22aa2f19ff33.jpg)
![revised_brown_bee](https://cloud.githubusercontent.com/assets/10438537/13165975/ef481502-d67f-11e5-9ede-a0607758307c.jpg)

Hi All -

Thanks for all of the feedback and kind words.  I present for your consideration an amalgam (with compromises) of the previous ideas.  Outlined wings but more subtle outlining, for use over dark and light backgrounds.  Slightly darker brown on the head and legs. No reason we couldn't have a transparent winged version along with an opaque is there?

-Sam

**Comment by warpling** [comment]
🐝💛

**Comment by andru** [comment]
<3

**Comment by elioqoshi** [comment]
Love this! Now just to find a way how to combine the wordmark well with it :D

**Comment by simonv3** [comment]
Thanks so much for all your work on this @sbchittenden. The bee looks great. 

@elioqoshi I think how @sbchittenden had arranged OpenFarm here under the bee pretty good https://cloud.githubusercontent.com/assets/10438537/13122264/5b7c908a-d573-11e5-8ea3-6db227c9b99a.jpg (but with a new bee). I don't see the mascot as part of the logo necessarily!

**Comment by elioqoshi** [comment]
@simonv3 well, it doesn't fit really. The wordmark is light and the bee has darker colors. Even if not used together, they should be in the same color spectrum (at least when on the same page, artboard, or canvas)

**Comment by sbchittenden** [comment]
So we are comparing apples to apples re: the wordmark and bee together, I have put together some variations of the current bee over different backgrounds with some re-colored wordmarks:

![openfarm_bee wordmark_2](https://cloud.githubusercontent.com/assets/10438537/13198846/445ddeb2-d7d1-11e5-8e11-163e0545909a.jpg)
![openfarm_bee wordmark_3](https://cloud.githubusercontent.com/assets/10438537/13198849/445f9aea-d7d1-11e5-9f30-7a62a616f9cd.jpg)
![openfarm_bee wordmark_4](https://cloud.githubusercontent.com/assets/10438537/13198850/446316e8-d7d1-11e5-8111-402f828a7566.jpg)
![openfarm_bee wordmark_5](https://cloud.githubusercontent.com/assets/10438537/13198847/445ed3ee-d7d1-11e5-9dc4-8231aca49867.jpg)
![openfarm_bee wordmark_7](https://cloud.githubusercontent.com/assets/10438537/13198848/445f4590-d7d1-11e5-8987-cc7ef8858eab.jpg)
![openfarm_bee wordmark_1](https://cloud.githubusercontent.com/assets/10438537/13198851/4d784a50-d7d1-11e5-9d95-b7f81d2d999c.jpg)

**Comment by sbchittenden** [comment]
Not sure how you guys are envisioning the use of the bee (whether it is used in tandem with the wordmark or not) but I feel it works well if need be with the wordmark (like on a sticker, or t-shirt, etc.). Thoughts?

**Comment by roryaronson** [comment]
I think the latest iteration of the bee is looking great, and I think it works well with the wordmark.

My guess is we won't often (ever?) use the bee and wordmark together as one 'logo', rather we'll use the bee throughout the site and other materials as a mascot, "face of OpenFarm", and a guide/helper to our members.

**Comment by sbchittenden** [comment]
:+1: :+1:

**Comment by roryaronson** [comment]
Based on the hearts above, it sounds like we agree that the bee is looking good, perhaps finalized?

If so, @sbchittenden could you upload the necessary files we'll need to use the bee? (source files, png in various sizes, and svg - all with transparent backgrounds)

**Comment by sbchittenden** [comment]
Will do.  I probably can't get to it until sometime tomorrow. Bit of a GitHub noob - Do I upload files in this thread? Or do a pull request with the new files? :blush:

**Comment by roryaronson** [comment]
You can attach files by dragging them into these comment boxes. Or if its easier for you could upload them to dropbox/google drive and just share a link :)

**Comment by sbchittenden** [comment]
Perfect

**Comment by sbchittenden** [comment]
@roryaronson 
Here is a link to the final OpenFarm bee files.  Let me know if you have any problems getting these or if there are other file formats you need.

https://www.dropbox.com/sh/0zmz0mbqe0aouqa/AABTb2P2Ryf5-yJqv1zL-CbDa?dl=0

**Comment by warpling** [comment]
This happened so fast!

**Comment by jsimplicio** [comment]
:+1: Bee looks great, welcome little mascot!

**Comment by roryaronson** [comment]
Thanks so much @sbchittenden!!

Now for the last order of beesiness - what's the bee's name? I'll throw some into the ring that I found on Yahoo Answers :stuck_out_tongue_closed_eyes:, Reddit, and the Goog. I bolded my favorites.

Classic/obvious:
* Buzz
* Bumble

Punny:
* **Phoebe**
* (Justin) Bieber
* **Obi-Wan Kenobi**
* **Beebee**
* Polly (like pollen)
* Herby
* Beatrice
* **Shelby**
* Albany 
* Colby 
* Abigail 
* Bianca 
* Bea

Geeky/Clever:
* **[Apidae](https://en.wikipedia.org/wiki/Apidae)**

**Comment by warpling** [comment]
Kenobi for sure.

**Comment by sbchittenden** [comment]
+1 Kenobi
(Ken O. Bee)


On Mon, Feb 22, 2016 at 3:41 PM, Ryan McLeod <notifications@github.com> wrote:
Kenobi for sure.

On Mon, Feb 22, 2016 at 2:17 PM Rory Aronson <notifications@github.com>
wrote:

> Thanks so much @sbchittenden <https://github.com/sbchittenden>!!
>
> Now for the last order of beesiness - what's the bee's name? I'll throw
> some into the ring that I found on Yahoo Answers [image:
> :stuck_out_tongue_closed_eyes:], Reddit, and the Goog. I bolded my
> favorites.
>
> Classic/obvious:
>
> - Buzz
> - Bumble
>
> Punny:
>
> - *Phoebe*
> - (Justin) Bieber
> - *Obi-Wan Kenobi*
> - *Beebee*
> - Polly (like pollen)
> - Herby
> - Beatrice
> - *Shelby*
> - Albany
> - Colby
> - Abigail
> - Bianca
> - Bea
>
> Geeky/Clever:
>
> - *Apidae <https://en.wikipedia.org/wiki/Apidae>*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/639#issuecomment-187413916>
> .
>
—
Reply to this email directly or view it on GitHub
[https://github.com/openfarmcc/OpenFarm/issues/639#issuecomment-187420952] .[https://github.com/notifications/beacon/AJ9Hia_f9DjYjvMHg9wtRkzJuHw1b-eqks5pm4X_gaJpZM4EbEL-.gif]

**Comment by elioqoshi** [comment]
Love it! I'd also go with "Polly"

**Comment by simonv3** [comment]
:+1: Ken O. Bee

**Comment by elioqoshi** [comment]
You should try to create an identity on your own, not borrowing anything from other franchises. While it's funny for a project, it should not be used for any serious project like this, IMO :)

**Comment by simonv3** [comment]
You're probably right. But still. It's hard to give up on such a good pun.

**Comment by andru** [comment]
I hate to throw more committee direction into a creative process, but it would be sweet if the name was more gender neutral than Ken. It gives it a pretty strong male vibe in any place that has Ken and Barbie dolls :) 

How about Obi? Obee? Obie?  I've only met guys named Obi but it's not as clearly gendered as something like Ken.  It also pulls it away from StarWars enough to be a pun in it's own right.

I like Bea, too. Although it sounds a bit like Beer. It's also a diminutive for Beatrix in Spanish so my head automatically pronounces it as Bey-ah. But I guess a lot of the audience wouldn't have that problem.

Zumbe is the third person present of Zumbir (to buzz) in Portuguese... ie. he/she/it buzzes. Zumbee? Sounds a bit like Zombie though.

Some words to do with bees from Portuguese/Spanish incase they inspire anyone:
Colméia / Colmena (hive)
Abelha / Abeja (honey bee)
Abelão / Abejorro (bumble bee)
Mel / Miel (honey)
Zumbir / Zumbar (to buzz)
Zumbi / Zumba (it buzzes)

**Comment by itanny999** [comment]
I found a posting on http://opensourcedesign.net/  . After reading the comments on a Honey-bee approach, this is what I got on canvas. There can be various facial expressions for different scenarios (Ex. Sad face on an error page, The bee carrying a honey bucket on loading page, etc.)
![openfarm-mascot](https://cloud.githubusercontent.com/assets/1792863/14881618/7152320e-0d52-11e6-9db0-6fd9070c4b72.png)

**Comment by simonv3** [comment]
@itanny999 Thanks for the thoughts and the sketches! I like the idea of playing with the facial expressions. Your bee looks friendly and welcoming :)

I think we're pretty set on @sbchittenden's final version in https://github.com/openfarmcc/OpenFarm/issues/639#issuecomment-186672367 though. I guess the topic is still open because we should choose a name. 

I actually quite like Mel a lot as a name? It's pretty gender-neutral, and I also like the honey connotation.

**Comment by simonv3** [comment]
Okay, I'm going to close this issue because it sounds like Obi is a favorite, and we had a conversation about this in Slack a while ago. 

Meet Obi, the OpenFarm bee :)

![obi](https://cloud.githubusercontent.com/assets/10438537/13198846/445ddeb2-d7d1-11e5-8e11-163e0545909a.jpg)

Thanks so much @sbchittenden for your fantastic work on this. Hopefully we'll be integrating Obi a bit more into our design as time progresses. Currently you can see them in [our readme.md](https://github.com/openfarmcc/OpenFarm/blob/master/README.md)

**Comment by roryaronson** [comment]
Hooray!!

**Comment by jancborchardt** [comment]
Really cool work @sbchittenden! :) I invited you to our collective at https://github.com/opensourcedesign as well.
