### ISSUE TITLE
Guides aren't perceived as completed.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#640]
From an email I received: 

> I went on the site, but I don't see any complete guides, am I looking in the wrong place? Most of them must look like this https://openfarm.cc/en/guides/cherry-tomatoes.  Maybe it's just the timelines seem incomplete.

I can see where people are coming from with that.

**Comment by roryaronson** [comment]
Yea this is definitely an issue in my opinion, and mostly can't be fixed until Guides can be reliably created.

**Comment by simonv3** [comment]
I'm going to close this because it's not really actionable.
