### ISSUE TITLE
Update crop data format

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#641]
To be more meaningful, some changes should be made to our crop data:

* [x] Add specific binomial name objects (genus, cultivar, etc)
* [x] Indicate parent crops through a link

This would be a pretty good newcomer/intermediate job to do. It would involve:

1. Adding fields to a crop (`genus`, `species`). Decide whether this makes sense as separate fields, or as a hash. 
2. Adding a parent field to a crop that refers to another crop.
3. Once it's all done, pushed, and merged, open an issue to parse the existing crops and figure out the right fields. 

If you have any other data that you think should be included, let me know! @roryaronson @RickCarlino @andru

A lot of this conversation happened here already: https://github.com/openfarmcc/OpenFarm/issues/60

**Comment by roryaronson** [comment]
That sounds good to me. In addition, we might want to add a field for a wikidata identifier/link. We could also have fields to the crop on other notable databases like Wikipedia and EOL.

**Comment by simonv3** [comment]
@roryaronson that should be easy to achieve, do you want to make a separate issue for it?

**Comment by simonv3** [comment]
This has actually been done for a while. Just need to do #682 and #683.
