### ISSUE TITLE
Crop titles not showing correctly on search results on iPads

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#642]
![image](https://cloud.githubusercontent.com/assets/5524043/7848516/42d4d1f0-0481-11e5-8219-a95f764b8487.jpg)

**Comment by simonv3** [comment]
Hey @roryaronson I can't reproduce this on any of the ipad simulators on iOS (which are supposed to be fairly good) or at any size just web browser wise. 

I also can't really pinpoint what would be causing this within the CSS, it all seems to make sense.

Can anyone else with an ipad double check this?

**Comment by warpling** [comment]
Works fine on my iPad (note: not mini) in both orientations











~Ryan

**Comment by roryaronson** [comment]
This happened on my Mom's first gen iPad. Maybe its been resolved since I filed the issue? Let's close it for now.
