### ISSUE TITLE
Member profile header loads slowly

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#643]
It seems that my Guides load first and very quickly, then my Gardens take a while to load which is fine, then once those are done the header (with my favorite crop image and profile picture) loads. This then akwardly pushes everything down. Is there a way to tell the browser (or format the page) such that the header loads before my Gardens?

Video:
https://drive.google.com/file/d/0B-wExYzQcnp3LVhzMGQ1VjBfd0E/view?usp=sharing

**Comment by Vincentdc94** [comment]
preload the images with javascript. Execute the preloader before the rest of the code. And make it preload the header first.

the code is easy: https://perishablepress.com/3-ways-preload-images-css-javascript-ajax/
