### ISSUE TITLE
Guides don't actually say what crop they're for.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#645]
Oops!

This would be an excellent opportunity for someone new to the project to get involved and fix this.

Steps that might need to be taken:

0. Have a look at the guide page and see where it makes sense to insert the name.
1. Open the right page view for the guide - `views/guides/show.html.erb`
2. Find the spot in the HTML (make sure to also look in the `/show/` folder for all the partials) where the name would make sense.
3. Insert the name of the guide using angular brackets, or ng-bind (ex. `<h2 ng-bind="guide.name"></h2>` or `<h2>{{ guide.name }}</h2>`). 

If you need any help, let me know!

(@emily-plummer, this is what I was thinking as newcomer instructions, does that make sense to you?)

**Comment by emily-plummer** [comment]
@simonv3 yeah I think this is great!

**Comment by Cynaria** [comment]
Hey, I just whipped something up for this. I'll send a pull request.

**Comment by roryaronson** [comment]
Awesome, thank you @Cynaria! PS, I sent you a Slack invite a few hours ago, welcome!

**Comment by roryaronson** [comment]
This is slightly broken on staging. It says the Crop name, but the link is wrong - goes to a 404
![capture](https://cloud.githubusercontent.com/assets/5524043/8892268/a10a07e8-3304-11e5-87bd-8c658ddbbd25.JPG)

**Comment by simonv3** [comment]
Fixed now.
