### ISSUE TITLE
Ambiguous Buttons

### ISSUE THREAD

**Issue by emily-plummer** [openfarmcc/OpenFarm#648]
![image](https://cloud.githubusercontent.com/assets/8960591/8093704/7a6e110c-0f77-11e5-95cb-bea859dbcbb0.png)

This is on the profile editing page. I don't know if I need to press one of these to save... they are a little confusing. I "Do it later" supposed to only show for people going through a intro to the site process?

**Comment by warpling** [comment]
It’d be helpful to provide some an actionable idea of how they could be improved/clarified. 

~Ryan

**Comment by emily-plummer** [comment]
I guess I'm just trying to ask someone if this button is necessary to save the information or does it just bring you back to the profile page?

If saving:
"Save" or "Discard Edits"

if going back to the page: 
"Go back to profile page"
and no second button @warpling

**Comment by warpling** [comment]
Hmm I think _save_ could be confusing when nothing has necessarily been entered/changed (a valid state when setting up your profile for the first time?), but maybe _discard edits_ is clear.

**Comment by emily-plummer** [comment]
I think the current buttons make sense when going through the wizard when you first sign up, but they should be changed to Save/Discard edits when you are viewing them outside of the wizard.

**Comment by roryaronson** [comment]
^ Yes to @emily-plummer's last comment!
