### ISSUE TITLE
Document All Flows Through the Application

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#659]
It'd be great if we could document _all_ flows through our application.

I have this in mind to be able to test the front-end properly. Something like Selenium could build these tests beautifully.

This would be great for a newcomer to get involved and better understand the project. Look at the wiki page for examples. @roryaronson you probably know this best at the moment.

https://github.com/openfarmcc/OpenFarm/wiki/User-Flows

**Comment by roryaronson** [comment]
I just did most of these, though there are plenty more I'm sure

**Comment by simonv3** [comment]
Yeah, I've been adding them as I've been testing things on the front-end. Keep on discovering new ones.

**Comment by simonv3** [comment]
I'm going to close this because it's never going to happen.
