### ISSUE TITLE
'Where does this stage happen' selector not showing

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#669]
This is on staging on the guide creation flow. Perhaps we want to ignore this in lieu of Guide Creation Flow V2. 

![capture](https://cloud.githubusercontent.com/assets/5524043/8892395/1b209c7c-330a-11e5-9912-903e17285692.JPG)

**Comment by roryaronson** [comment]
:Looks like the soil type and sunlight options aren't all showing up either:
![capture](https://cloud.githubusercontent.com/assets/5524043/8892421/03ad03ea-330b-11e5-9f5f-9c5f0ebe6be9.JPG)

**Comment by simonv3** [comment]
This very possibly has something to do that these things aren't created in the backend on staging yet.
