### ISSUE TITLE
Add warnings for Toxicity in crops

### ISSUE THREAD

**Issue by tkeifer** [openfarmcc/OpenFarm#676]
I noticed in your list of crops you have some poisonous varieties listed (such as baneberry and hemlock) there should probably be an indicator of potential toxicity. You could have icons that act as a quick visual indicator maybe? Some plants may only be partially edible. (ex... roots are edible, while fruit and/or leaves are not)

**Comment by simonv3** [comment]
That's a really good idea @tkeifer. 

Do you have any ideas for maybe breaking that down to create some sort of hierarchy? That way we can decide how that fits within the data, and create visual steps icons for it. 

If anyone wants to take a stab at defining that, or sketching some visual icons, that would be awesome.

**Comment by simonv3** [comment]
So, we could have a tag system that both guides and crops embed. 

This way crops can be tagged as `toxic` or `toxic to certain individuals`, and guides as `uses pesticides` etc.

**Comment by tkeifer** [comment]
This is along the lines of what I was thinking. You could have a single warning badge (like the toxic label on cleaning products) and then reference an entry in the database to explain the specifics.

**Comment by roryaronson** [comment]
Yea this sounds really great! Maybe the member badges list UI element could be made modular and used for the Crop and Guide tags as well?

@tkeifer, we've discussed a bit about the tagging system in this [blog post about content policies](http://blog.openfarm.cc/2015/06/10/taking-a-stance-our-content-policies/) and also in the [Slack channel](slack.openfarm.cc). I'm wondering what types of tags we should have. Should we go simple at first and just have a few that we come up with? Or build a system where people can type in whatever they want, and we have an auto-complete feature like typing in hashtags on Twitter or Instagram?

**Comment by tkeifer** [comment]
IMHO, start with something minimal. You have a great foundation, but still a lot of ideas to implement. Code tends to balloon fast and become unmanageable. Study user behavior and solicit input frequently. Let the community show you the way - if solving it adds to the fundamental objective with the project, go for it!

**Comment by TanSA05** [comment]
@simonv3 How do we know which crops are toxic? Does the user enter that when he's filling out the guide form? Also, do we have a customized icon for denoting the toxic nature of a particular crop, or would we go with the general `!` in a triangle warning label?

**Comment by simonv3** [comment]
I think this would be a tag list in the crop edit form. An input field that is comma separated, maybe with dropdown suggestions of existing tags. In the future we can limit adding tags to crops to a certain group of people, but for now everyone should be able to do it.

I imagine something like 

## Poison Berry

`toxic` `shrub` `etc.`

right underneath the images for the Poison Berry in the crop page. Does that make sense?

**Comment by TanSA05** [comment]
@simonv3 @roryaronson Thoughts about showing the user some tags when they first see the stage 4 of the new guide form?
For example: When I first load that page, 4-5 tags are present in the field already. I have the choice to delete them.
Also, if we display some tags then, what should decide which tags are being displayed? I was thinking that we could display the first 4 or 5 in the descending order of their weights.

**Comment by simonv3** [comment]
@TanSA05 I like that idea, but it sounds like you're proposing this for guides, whereas this ticket is for crops!

**Comment by TanSA05** [comment]
@simonv3 No, I'm talking about crops. The Crops are tagged, however you can only add tags to them via the Guide form, right?

**Comment by simonv3** [comment]
Nope! You should be able to add them on crops/edit.html.erb.

**Comment by TanSA05** [comment]
Right, thanks! :D
