### ISSUE TITLE
Make Shared Image be the image of the crop rather than just the openfarm image. 

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#678]
This is about the image that gets shown when a page gets shared with Twitter and Facebook and other social media accounts. 

This is enabled in [_social_network.html.erb](https://github.com/openfarmcc/OpenFarm/blob/master/app/views/meta/_social_network.html.erb#L1), where the page looks for a :title, :description, and :social_image. Then in each template for each specific view of the app (crop, crop search results, guides, and user profiles) those pages should provide content for those fields. Eg, this is already done for [crops](https://github.com/openfarmcc/OpenFarm/blob/master/app/views/crops/show.html.erb#L1). 

It could be that this already done for a number of these. Also make sure to cut off the description to about 140 characters. 

Do this for:
* [x] Crops (use the first image)
* [ ] Crop search results (use the image of the first crop)
* [x] Guides (use the first image)
* [ ] User profiles (use the favorite crop)

Then ideally, if it's possible to find a way to test this that would be great. We'll be able to test on staging for sure.

**Comment by simonv3** [comment]
Oh, and make sure the description of something gets cut off.

**Comment by TanSA05** [comment]
@simonv3 @roryaronson Hey! Can you clear which "Guides" you're talking about in the 3rd checkbox?

**Comment by TanSA05** [comment]
@simonv3 I'm just confused because it seems like the code is already written in `guides/show.html.erb`

**Comment by simonv3** [comment]
@TanSA05 that's possible! Like I said in the description: "It could be that this already done for a number of these." :)

**Comment by TanSA05** [comment]
Okay! Just the tests are left now, then! :D

**Comment by TanSA05** [comment]
@simonv3 Closed! :D
