### ISSUE TITLE
Make images that are being uploaded through delayed jobs appear as "still uploading"

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#680]
This will make things smoother for users.

Related to #609.

**Comment by simonv3** [comment]
Some notes: 

https://stackoverflow.com/questions/4600480/rails-3-delayed-job-how-can-i-keep-track-of-progress-of-a-task-e-g-progress

https://stackoverflow.com/questions/4635586/delayed-job-keeping-track-of-objects-progress?rq=1

https://stackoverflow.com/questions/6052546/rails-how-do-i-display-the-progress-of-the-delayed-job-queue?rq=1

https://github.com/d4be4st/progress_job (works with delayed job to show progress)

**Comment by simonv3** [comment]
@roryaronson I have implemented this really basically on staging for crops. It shows a little loading circle when the images are still being processed and then shows the images when complete. What do you think?

**Comment by roryaronson** [comment]
Just tested:

The image uploads, I press 'Save Crop', it redirects to the crop page, but there is no loading spinner. If I then refresh the page, the loading spinner shows up, and it is eventually replaced automagically by the processed image.

**Comment by simonv3** [comment]
hmmmmmm. I suspect I know why that's happening.

**Comment by simonv3** [comment]
Think I fixed this, try now?

**Comment by roryaronson** [comment]
It works!

I think the spinner is a little confusing. My first impression is that the image is 'loading', rather than 'processing'. Maybe the spinner + some light colored text that said 'processing' would help?

**Comment by simonv3** [comment]
I want an icon that translates roughly to "bleep bleep bloop bloop"
