### ISSUE TITLE
Crop Icons

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#685]
As most folks here know, I'm working on another open-source project called [FarmBot](https://github.com/FarmBot/farmbot-web-app). We're starting to build a drag and drop farm designer/manager tool where one can graphically layout and keep track of plants on a map. A core visual component of this will be crop icons that visually represent the plants.

We'd like to have these icons hosted on OpenFarm so we can tap into the community at-large to help create/maintain icons for a bunch of Crops. This would be useful to OpenFarm because a) FarmBot could pay for usage of the API, b) OpenFarm would be more prepared for when (if) the farm designer tool is ported to it, and c) it's another piece of cool openly licensed content that would likely have a bunch of other use cases such as in @andru's hortomatic, or other apps using the API.

I imagine if we built this feature, it would be just another part of the Crop model. Currently we have Crop images, we could also have Crop icons. They would just have to be .svg's.

What do you think?

**Comment by andru** [comment]
I started some rough initial work on this for [Hortomatic](http://hortomatic.com) last winter, and the plan is to flesh out an initial common crop set this winter.  I'm open to using this opportunity to collaborate on an openly licensed set of crop icons.

Hortomatic is stylistically playful, using simple geometric forms and a wide colour palette and I'd like that to be reflected in the crop icons.  Clearly the style I want for Hortomatic is not going to suit all projects, but I think an open set in SVG could be based on simple silhouette forms with line and fill options set via CSS to allow different projects to define their own colours, line weights etc  from the core set of forms.  See [Iconic](http://useiconic.com) for a good example.

That complicates things quite a bit more than I was planning for the set for Hortomatic, so I'd need to find another collaborator to help out.

**Comment by simonv3** [comment]
You could post something on https://github.com/opensourcedesign/jobs#job-board and see if any of the designers there might be interested in working together.

**Comment by roryaronson** [comment]
Just submitted a posting!

@andru, an icon set like Iconic would be ahhhmazzinnngg. If you can teach me how to make icons out of code like that, I'm happy to help make a few dozen.

Or maybe I can help in other ways. Like digitally drawing plants?

What is the process and tools needed to make the icons like those in Iconic?

**Comment by roryaronson** [comment]
Just put out some tweets and Facebook posts about this. Also sent out an email to 800 peeps on the FarmBot list. Once we get those backer badges in, I'll send out an announcement of that feature (and the member profiles feature!) and a call for help on this + the guide creation flow V2.

These icons would be so cool :grinning:

**Comment by simonv3** [comment]
:+1:

**Comment by benvickers** [comment]
@olamoller ping!

**Comment by neynah** [comment]
I'm pretty interested in helping out with designing icons if you guys still need help. :)

**Comment by simonv3** [comment]
@neynah As far as I know, I don't think any progress has been made on this. @roryaronson probably knows best for what he has in mind, but I think the concept is pretty straight forward. We're looking for a couple of icons for standard (most likely the most popular) crops.

From our website's community favorites - 

* tomatos 
* cherry tomatoes, 
* strawberries
* carrots
* lemons
* tomatillos (?)
* radish
* orange
* corn

from the top of my head:

* passion fruit
* onions
* shallots
* cucumbers
* pumpkin
* beets
* 

I don't think detail is as important as general idea, and it might be possible to do generalized concepts (groups) too: squash, tomatos, citrus, root vegetables, etc.

**Comment by andru** [comment]
@mstenta ping! This may be useful for FarmOS.

@neynah Your help would be awesome.

I'm getting close to needing to work on this for Hortomatic. I guess it would be good to pull together a rough style guide so that the icon set can be worked on by multiple authors.

I think the style of the [Foodies](https://ui8.net/product/foodies) set is great. If we make an SVG icon set we could go for a geometrically simple style like that with stylesheets for line, single fill, and multiple fill styles.

For line icons, I love the style of [this small set by Thiago Sanchez](https://dribbble.com/shots/1667493-Vegetables-and-Fruits), but they might be a bit too distinctive for a set designed to be shared between projects.

Anyone else have some stylistic direction to pitch in?

**Comment by andru** [comment]
![Uploading Screen Shot 2016-01-14 at 19.12.20.png…](http://apps.timwhitlock.info/emoji/tables/unicode)

Also, these from the UTF emoji block. Not openly licensed, but some good hints on forms for a few common crops.

**Comment by simonv3** [comment]
@andru I think it'd be useful if we made a list of crops we'd think we need. What's in that UTF block and the list I mentioned earlier are probably good starting points. We can probably put it on this wiki - or in the crops repo, and then gather icons in a folder there. What do you think?

**Comment by andru** [comment]
Maybe we should set up a new repo for it?  I can see there being a lot of conversation and issue tracking to get a decent sized icon set.

openfarmcc/open-crop-icons ?

**Comment by simonv3** [comment]
Have at it: https://github.com/openfarmcc/open-crop-icons

**Comment by roryaronson** [comment]
Foodies icon set style is :+1: :+1: So are standard emojis IMO.

I had one person helping me out a little, but they fell off after a few emails. They did send me this stuff though which I think is pretty spot on:
![capture](https://cloud.githubusercontent.com/assets/5524043/12380119/40210c56-bd1f-11e5-9917-1cd9d43121b4.JPG)

**Comment by roryaronson** [comment]
Foodies icon set style is :+1: :+1: So are standard emojis IMO.

I had one person helping me out a little, but they fell off after a few emails. They did send me this stuff though which I think is pretty spot on:
![capture](https://cloud.githubusercontent.com/assets/5524043/12380119/40210c56-bd1f-11e5-9917-1cd9d43121b4.JPG)

**Comment by neynah** [comment]
I think the foodies set style is great. I can start with some from your list @simonv3?

"tomatos
cherry tomatoes,
strawberries
carrots
lemons
tomatillos (?)
radish
orange
corn"

**Comment by simonv3** [comment]
@neynah that looks like a really great list to start with. Please go ahead! 

Also have a look here: https://github.com/openfarmcc/open-crop-icons/issues/2. 

On a note - I don't think it can hurt to have multiple of the same crop.

**Comment by simonv3** [comment]
I'm going to close this issue for now because the conversation is pretty rocking in https://github.com/openfarmcc/open-crop-icons/issues/2
