### ISSUE TITLE
No way to access openfarm.cc with chrome (last version) due to NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by mo22de** [openfarmcc/OpenFarm#687]
Hey long time no see but actually an important reason to get back to you now.

I discovered that the latest chrome version dont allow showing the opefarm.cc website at all.
It seems to be a general SSL issue and may can be solved replacing the webservers ssl certificate.

My chrome tells me that the certificate is timed out and was dated like this:

10.09.2014 to 11.09.2015

it works just when one uses

http://www.openfarm.cc/

but NOT 
http://openfarm.cc
or https://openfarm.cc

so it seems like the subdomian or alias isnt forced into SSL at all.

Maybe its another problem as it seems a bit wiered and maybe its hard to figure it out.
So as an alternative one could just try to change in OpenFarm/config/environments/production.rb

Line 11    config.force_ssl = true

to => config.force_ssl =false

to test it.

But hey if its just the server certificate replace it and everything is good. 
If that doesnt help one may need to get a closer look

For example at the config of the RackAttack gem as it seems this replaces the standard rack-ssl gem as i didnt found it in the gems-files.

So this should be an important issue and info if not allready noticed.

Hope this helps

sheers :)

**Comment by simonv3** [comment]
Hey @mo22de! Thanks for the report. We've actually been having some issues with the certificates - they were re-issued but we no longer have the key by which they were originally generated. (I think that's right - @roryaronson, @RickCarlino?) I think Rick switched off the certificate, but we may not have set the force_ssl thing back. I'll do a push for that just now.

If we can't get the certificate working I'm happy switching SSL off completely for now and waiting until [letsencrypt](http://letsencrypt.org/) starts working - the 17th of November. <3 free things.

**Comment by simonv3** [comment]
Looks like it's been fixed. Thanks Rick!
