### ISSUE TITLE
Add Kickstarter Backer Badge

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#690]
I have a list of our backer's emails. Is there a systematic way we can give the Backer Badge to them?

**Comment by simonv3** [comment]
I'd have to write an import script and run it on the server. That's not an issue though - send it to me :)

**Comment by roryaronson** [comment]
Just sent it over!

**Comment by simonv3** [comment]
This is done. Have a look at kevin's page: https://openfarm.cc/en/users/5407387f63373700020f0000
