### ISSUE TITLE
Move editing guides into a inline-editor

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#695]
I'm starting to think that instead of routing a user back through the same flow to create a guide for editing a guide, to move guide editing inline. 

Eg. when a user is viewing their own guide, they see "edit" buttons here and there.

Have we had this conversation? 

* [ ] Edit individual stages
  * [x] Edit environment things
  * [x] Edit actions #698  
  * [x] Remove a stage
  * [x] Add a stage
     * [ ] Choose type of stage
     * [ ] Choose order
     * [ ] Choose basic stage details (environment variables)
     * Then let everything else be managed by the stage editing process. 
  * [ ] Edit images #699
  * [ ] Save and edit button for individual stages
* [ ] Edit featured image
* [ ] Show guide practices as part of "matching". 
* [ ] Don't delete actions when they already exist on editing stage steps. #700

Thoughts @roryaronson @warpling

**Comment by roryaronson** [comment]
I like that idea. We had talked about WYSIWYG guide creation, but decided against it because it would be overwhelming to see a blank guide. Once it's made though, edit buttons + inline editing makes more sense I think because then the editor can see all the surrounding context while editing

**Comment by simonv3** [comment]
This would simplify the code on the new guide creation page a lot too.

**Comment by simonv3** [comment]
This list has been overwritten by #722.
