### ISSUE TITLE
Refine Deleting Images

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#703]
I'm making a Guide and I accidentally uploaded an image to the wrong spot. To delete it, I clicked it, and it became highlighted in red with a trash can, but then it can't actually be removed until (I think) I save the Guide. If I upload another image, then it de-marks that image for deletion.

I think it would be easier if each image had a small link under the image to delete it, and clicking that link actually deleted it right there. I don't even think it needs a confirmation dialog because at worst, the author just uploads it again cause it wouldn't be deleting off their computer.

**Comment by simonv3** [comment]
That makes sense to me. That's a whole lot easier too.
