### ISSUE TITLE
Guide Creation Page Footer Doesn't Stick

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#705]
As the guide content expands vertically, the footer gets all wonky
![capture](https://cloud.githubusercontent.com/assets/5524043/12061108/be1c09b2-af32-11e5-8af6-6b4ead954c67.JPG)

**Comment by simonv3** [comment]
Dang, yeah, this is because of the fading toggles on the guide creation stuff. Alternatives are to rewrite the flow so that it doesn't use `position: absolute` or to recalculate the height of step_3 container periodically.

**Comment by simonv3** [comment]
I'm fairly sure this is fixed.
