### ISSUE TITLE
Multiple life stages can't have different environment/light/soil

### ISSUE THREAD

**Issue by mstenta** [openfarmcc/OpenFarm#709]
Just playing around with OpenFarm for the first time... I think I discovered a small bug.

Check out the guide I created here: https://openfarm.cc/guides/569c0e1d3c9839000300009f/

I added all the Life Stages - but it doesn't seem that I can change the Environment/Light/Soil values for each stage.

Possible clue: If I click on a different life stage (not Preparation), and click "Partial Sun", and then click back to "Preparation", it shows BOTH "Full Sun" and "Partial Sun" - and it saves both to that Life Stage, not the other.

**Comment by roryaronson** [comment]
It sounds like an issue with the editing, not with the creation. @simonv3 recently refactored the whole guide creation flow and moved guide editing to be in-line with the guide. I'm pretty sure that the part you're trying to edit isn't a feature yet :)

**Comment by mstenta** [comment]
Yea - it seems like a UI issue, not necessarily with the underlying data architecture.

Here's a screencast of the issue, if that helps: http://imgur.com/WkvgrBm

**Comment by simonv3** [comment]
@mstenta screencasts are very helpful, and thanks for taking time to report this!

Like Rory said - we did a huge rejig of all the guide flow, and editing is only half-baked still. Do you have any interest / time to investigate this? (Doesn't hurt to ask, and that way we could test our yet to be published Vagrant dev environment - if you do, I can give some background on what you're probably looking for - it'll be an Angular scope issue most likely).

**Comment by mstenta** [comment]
@simonv3 Cool - I really like the UI in the site in general - Nice work on the rejig. :+1: 

I have zero experience with Angular - so I doubt I could easily help - that, and my own debugging plate is full as it is... :-)

I do have experience with Vagrant - I use it for all my development, along with Puppet for automated provisioning.  Perhaps I could help test that out for you sometime, at the very least.

Just clone the repo and `vagrant up`?

**Comment by simonv3** [comment]
Yeah, I figured! 

`vagrant up` is the hope!

**Comment by mstenta** [comment]
`vagrant up` seems to work well!  Although I did have an extra step to tell it where to get the Ubuntu box from. I created a pull request that solves that, if you're interested: https://github.com/openfarmcc/OpenFarm/pull/710

**Comment by roryaronson** [comment]
:+1: Thanks @mstenta! What type of computer (OS) did you test it with?

**Comment by mstenta** [comment]
@roryaronson I have only tested the `vagrant up` part of it - not OpenFarm itself yet (I'll need to set aside some time to do that in the near future).

I'm on Ubuntu 14.04.

**Comment by mstenta** [comment]
@roryaronson and @simonv3 regarding running Vagrant + Puppet on Windows: it's definitely doable. One of my co-workers is on Windows and I set him up with the Vagrant script that I use on Linux, and my other friend uses on Mac. So it works on all three OSes the same! Very useful!

**Comment by roryaronson** [comment]
Ok cool, the "Ubuntu 14.04" was the info I was looking for. Cause Simon uses a Mac (I think) and I'm on a Windows 10 machine. And for the longest time vagrant would work for Simon but not me. And we were untested on Linux.

**Comment by mstenta** [comment]
Cool! Well it works great! And it seemed to go through all the bootstrap.sh stuff successfully... looked like there was maybe a minor error here or there, but I don't think it was major. I ran `vagrant destroy` afterwards so I could test the pull request I just submitted - but I'll `vagrant up` again soon so I can play around with OpenFarm a bit. Right now I need to do some dev on my other VM though. :-)

**Comment by mstenta** [comment]
If I have some time, I might take a quick look into this issue I reported too - but chances are you'll get to it before me.

Just in case, though... could you perhaps give me a clue as to which file I might start looking in? Did I mention I know nothing about Angular? :-)

**Comment by simonv3** [comment]
Thanks for trying it all out. I'll have a look at your PR tomorrow morning - thanks for making it :)

`/angular-libs/guides/show/guides.show.stage.*` is probably the place that this is going wrong. There's both a template and a directive.js file to investigate.

**Comment by simonv3** [comment]
Just FYI, I'm investigating this right now.

**Comment by simonv3** [comment]
So the problem here was that the multiple select thing had a bunch of `<label for="x">` tags where the "x" was the same for each object, so when you clicked on the relevant button you were changing the value for the first id the page could find. Fixed by passing in a unique id. This might be a problem on other pages too.
