### ISSUE TITLE
Improve Life Stage Navigation

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#712]
When I go to my [passion fruit guide](https://openfarm.cc/en/guides/passion-fruit-vines-on-a-bike-wheel-dome-orgone-accumulator-1) and read through the first Life Stage, I have to scroll to get through it all. Then once at the bottom of the web page, I forget that there are other life stage tabs filled with content.
![image](https://cloud.githubusercontent.com/assets/5524043/12689056/2b1f1c0c-c68f-11e5-92f3-cc674f058944.png)

I see a few possible solutions to improve this:
1) Add the life stage tabs below the stage content. Drawback is that this would look weird if the content was minimal.
2) Add "Next Stage" and "Previous Stage" buttons below the stage content
3) Get rid of the tabs altogether and opt for all content to be displayed sequentially down the web page with clear Headers for the different Life Stages.
4) Make the life stage tabs 'Sticky' so that when you scroll, you don't lose the context of the overall section and the other stages.

**Comment by roryaronson** [comment]
I think my favorite possible solution is a combination of 2 and 4.

**Comment by jsimplicio** [comment]
Yep, 2 and 4 sound great, especially 4 it gives you context to where you are.

**Comment by simonv3** [comment]
This has actually been fixed a while ago! We went the sticky route. You can see it in action for the aforementioned guide: https://openfarm.cc/en/guides/passion-fruit-vines-on-a-bike-wheel-dome-orgone-accumulator-1
