### ISSUE TITLE
Better placement for 'create a guide' inside a crop's page

### ISSUE THREAD

**Issue by jsimplicio** [openfarmcc/OpenFarm#713]
Hey all I noticed the create a guide button is placed all the way at the bottom of all guides, therefore it's getting buried when there's a long list.

![screen shot 2016-01-29 at 4 16 43 pm](https://cloud.githubusercontent.com/assets/7318958/12690238/ac75db52-c6a7-11e5-8896-82385c41290a.png)

Since we're promoting the idea of more people generating content, it'd be better to move that action to a more visible place? Maybe similar to this example I made quickly:

![addguide](https://cloud.githubusercontent.com/assets/7318958/12690256/ceedb998-c6a7-11e5-83ee-692545aed96d.png)

**Comment by roryaronson** [comment]
I think that's a great idea! Another option is to take the existing UI element, place it at the top of the list, and change the text to "Make your own" (which I think would follow well after the "Guides for this crop" heading)

**Comment by simonv3** [comment]
I like the idea of moving this to the top, though let's not lose the one at the bottom (after a potentially long scroll!), and make sure to not show them both if there's only a handful of guides?

**Comment by jsimplicio** [comment]
Yeah if there's like less than 5 or 10 don't bother showing the one at the bottom

**Comment by simonv3** [comment]
This is a really great for someone new to the project hoping to explore Ruby on Rails' controller + view structure. 

1. Find where the guides and crops are shown (`views/crops/show.html.erb` and `views/crop_searches/show.html.erb`)
2. Copy the "Create Guide" button to the top. 
3. Add a conditional to the bottom to only show if there are more than 10 guides being shown.
