### ISSUE TITLE
Create a Manifest.json File

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#737]
Create a `manifest.json` file and include it:

```
<link rel="manifest" href="manifest.json">
```

https://developer.mozilla.org/en-US/docs/Web/Manifest
https://www.w3.org/TR/appmanifest/

The ideal here is to add it the <head> of the page, which will allow people to easily add openfarm to their phone as an "app". It's reminiscent of that xkcd comic about standards.

**Comment by anyangocynthia** [comment]
@simonv3 I am looking into this issue. Just realized that there is a manifest.json file that already exists and it has been linked. Is there more to be done or we close the issue. Please look into it.

**Comment by simonv3** [comment]
This isn't closed because last I checked it isn't working properly yet. The file was added, but not tested properly. Is that something you're willing to look into @anyangocynthia?

**Comment by anyangocynthia** [comment]
yes @simonv3

**Comment by anyangocynthia** [comment]
@simonv3 This seems to be working fine 👍 
![videotogif_2017 09 16_18 37 16](https://user-images.githubusercontent.com/6637113/30513622-00ae6012-9b0f-11e7-9ed8-2b7cb2a6131f.gif)

**Comment by simonv3** [comment]
Awesome!
