### ISSUE TITLE
Guide publish button needs to "reset" if Guide does not successfully save

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#738]
I made my guide but did not give an overview for some of the Actions. When I clicked to Publish the guide, the site served up some toast notifications saying that overviews were required for the actions. Ok, so I went back and added the overviews. Then when I got to the final screen to go click publish again, the button was still "spinning" from the first time I clicked it. There was no way to get it to reset for me to save my guide. So if a Guide fails to save, the site should serve the notifications of why it failed and then it should return to being clickable.

**Comment by simonv3** [comment]
We probably also don't need to require the "overview" bit on actions. Just having the action title is often indicator enough. Eg. "for the planting stage you need to: water" and that can just be the default. Maybe that should be its own issue?

**Comment by simonv3** [comment]
I'm fairly sure this was fixed a while ago! But what I'm doing some work now to make it clearer at each stage that things are not finished, and what users need to do to complete a stage.
