### ISSUE TITLE
Crop icons (place to upload)

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#742]
Just like Crop images, but for icons.

**Comment by roryaronson** [comment]
So the idea is that users would be able to upload icons from the edit crop page. The interface could be exactly like the interface for uploading images. There could be multiple icons for each crop. Like this ultra janky mockup:
![edit icons](https://cloud.githubusercontent.com/assets/5524043/17839362/25a4b758-679a-11e6-9d1e-4ae57c91ab35.JPG)


The icons would then be displayed on the show crop page in the table, kinda like this:

![icons](https://cloud.githubusercontent.com/assets/5524043/17839351/ede5278a-6799-11e6-982d-8b70ca0bcede.JPG)

**Comment by TanSA05** [comment]
@roryaronson Thanks for that! :) I'll get to work on it now.

**Comment by simonv3** [comment]
I'm revamping image uploading as part of this. Watch this space.

**Comment by simonv3** [comment]
This is done!

**Comment by roryaronson** [comment]
FYI, there are now over 100 icons hosted on OpenFarm and another 40 coming up this week! 🌱 🌱 🌱 🌱 🌱 🌱 🌱 🌱 🌱

**Comment by simonv3** [comment]
Tell me more about the money plant.

**Comment by roryaronson** [comment]
Well, when making dozens of icons one has to have a little fun, yea? I'm thinking we might make some lucky charms icons too hahaha 🌈 🌠 ❤️ 🌔 🎩 ☘️

**Comment by roryaronson** [comment]
https://openfarm.cc/crops/money-tree

**Comment by simonv3** [comment]
Yeah but how can I grow it?

**Comment by roryaronson** [comment]
Oh, I'm still working on the guide ;p

**Comment by simonv3** [comment]
Note: we need to add the icons to the crop view.
