### ISSUE TITLE
Can't de-favorite Guides

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#749]

**Comment by simonv3** [comment]
If you click on the favorite button again it should de-favorite it - is that not what you're experiencing @roryaronson?

**Comment by roryaronson** [comment]
Correct. When i press the favorite button again, the star goes back to gray/black making it look like I de-favorited the Guide. But if I refresh the page then it is still lit up. Also, if I go to my profile it still shows as one of my favorite guides

**Comment by simonv3** [comment]
hrmpf.

**Comment by simonv3** [comment]
Can you test this on staging? For me it works on there, but not on production. http://staging.openfarm.cc

**Comment by roryaronson** [comment]
It doesn't work for me on either

On Tue, Jun 21, 2016 at 4:22 PM Simon <notifications@github.com> wrote:

> Can you test this on staging? For me it works on there, but not on
> production. http://staging.openfarm.cc
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openfarmcc/OpenFarm/issues/749#issuecomment-227601407>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFRKSwfoGR1pEGIzX9ySaJbkIbXuy9kOks5qOHJBgaJpZM4I7Cjr>
> .
>
-- 
- Rory

**Comment by simonv3** [comment]
This should now be fixed on staging and production.
