### ISSUE TITLE
404 when creating new Crop

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#750]
1. Go create a new crop: https://openfarm.cc/en/crops/new
2. Press the save button and the page will redirect to a 404 at https://openfarm.cc/en/crops/undefined
3. If you go search for your Crop, it actually *did* get created

**Comment by simonv3** [comment]
Looks like a JavaScript bug.

**Comment by TheChirpyWitch** [comment]
Hey @simonv3 ! I fixed this issue.
