### ISSUE TITLE
"See how it works" dropdown should have higher z-index

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#762]
So that the top right menu does not block the 'X'
![capture](https://cloud.githubusercontent.com/assets/5524043/16707023/e49d0fde-4576-11e6-8f1b-324506cce8b7.JPG)

**Comment by jumbosushi** [comment]
Hello! I made a pull request at https://github.com/openfarmcc/OpenFarm/pull/769

**Comment by simonv3** [comment]
Thanks @jumbosushi! I've merged the PR and you should be able to see the changes on staging within 10 minutes or so: http://staging.openfarm.cc
