### ISSUE TITLE
Integrate tool for showing mails in development mode

### ISSUE THREAD

**Issue by kuldeepaggarwal** [openfarmcc/OpenFarm#764]
As there is no need to send actual emails in development mode, so we need to find a way that can open mails somewhere else (maybe in Browser) so that newcomers need not to dig dive into the logs. One utility can be [letter_opener](https://github.com/ryanb/letter_opener), but whosoever will pick this issue can also search for any other tool as well.

**Comment by simonv3** [comment]
This is very cool and will significantly change how our e-mails look. Thanks for the suggestion @kuldeepaggarwal.
