### ISSUE TITLE
Non-LoggedIn User shouldn't be able to mark guide as FAVORITE

### ISSUE THREAD

**Issue by kuldeepaggarwal** [openfarmcc/OpenFarm#765]
If a user is not logged-in and tries to access any guide url(`http://localhost:3000/en/guides/sky-blue-kemmer`) then he/she should not be able to mark the guide as `favorite`.

<img width="1430" alt="screen shot 2016-07-11 at 8 16 43 pm" src="https://cloud.githubusercontent.com/assets/1930730/16734856/a2cf3ed0-47a4-11e6-852a-7bba8ea7bc08.png">

**Comment by roryaronson** [comment]
We could either remove the Favorite button for non-logged-in people, OR when clicked by a non-logged-in person it could prompt them "You have to become a member to save your Favorite Guides"

**Comment by kuldeepaggarwal** [comment]
@roryaronson I may have a better option, we can show a message `Sign up / JoinIn for making it as your favorite guide` on button, so if user clicks on it and sign-up/signin then this guide should be marked as favorite.

**Comment by roryaronson** [comment]
I think we should avoid adding a lot of text on the button. Especially considering that there are many buttons/functions that require the user to be logged in and we wouldn't want to change all of those buttons to a "Join to do this thing" button cause that would be really redundant and feel desperate for signups (in my opinion). So I think a simple alert that prompts the user to sign up is the cleanest route to go. It also keeps the interface consistent between non-logged-in and logged-in people which is a plus in my view.

**Comment by kuldeepaggarwal** [comment]
Agree, but having popup(s) is/are not good UI for users, rather we should hide these buttons. wdyt?

**Comment by simonv3** [comment]
How about just redirecting them to the log in page when they click it? I don't think we want to hide the functionality because it's definitely a feature we want to advertise.

**Comment by roryaronson** [comment]
Agreed - we don't want to hide features. I'm thinking we would use the standard notification system we already have (in the top right). So, its not an obtrusive take-over-the-screen popup saying "Sign up!" but rather just a "Hey, fyi, you need to signup to do that"
