### ISSUE TITLE
User confirmation flow

### ISSUE THREAD

**Issue by kuldeepaggarwal** [openfarmcc/OpenFarm#766]
I am not sure what should be the exact flow for user confirmation, so creating an issue and ready to discuss before any hack/implementation.

```
If a user(say userA) is already logged in into the system and another user(say userB) tries to activate her/his account via confirmation link, then which user should be logged-in after confirmation?
```
- [ ] userA ??
- [ ] userB ??

\cc @simonv3 @roryaronson

**Comment by simonv3** [comment]
I think User A should be logged out and the confirmation should go to User B. I think User B should definitely not get access to User A's account, and I think logging User A out is the safest option.

**Comment by roryaronson** [comment]
I agree with Simon. Upon clicking a confirmation link User A should be logged out and User B should be logged in and have their account confirmed.

**Comment by kuldeepaggarwal** [comment]
@simonv3 @roryaronson This is exactly happening into the system, so I think we can close this issue.
