### ISSUE TITLE
Web interface effectively unusable for several hours

### ISSUE THREAD

**Issue by cailenfisher** [openfarmcc/OpenFarm#767]
7/13/16 - Immediately after creating my account I was only able to navigate to any page perhaps 2 out of every 10 times. The behavior varie,d but I observed "Bad S3 Response" and a few intermittent 503 errors in the browser console. Some page loads would come through but be incomplete, missing stylesheets and other assets, etc. After continually trying, the most consistent response was to get nothing from the actual website and instead just a empty page with an iframe displaying the aws hosted Heroku error page that just says "Application Error" without further information on the page or in the console.

**Comment by simonv3** [comment]
This might be something to take up with Heroku actually. 

@cailenfisher can you give us some details about operating system, browser, country you're accessing from, etc.?

**Comment by cailenfisher** [comment]
Chrome on Linux, located in Pittsburgh, PA, USA on a Verizon internet connection. 

It was definitely a server side issue rather than client glitches, as I inspected the DOM and it wasn't even loading your app.

The first day I did also see some S3 request errors but primarily the result was getting the Heroku "Application Error" (which should definitely show up in logs, concerning that it doesn't)

The one thing I can think of that might explain this seeming specific to me is possibly a bad session got set on the server since I was getting other issues during my first sign in - but that is a stretch since I made sure I logged out and back in yesterday and still got Application Error on the second page load.

I also just checked again and same behavior... I load the home page fine, then click 'Tomato' and after a long delay I get Application Error
![image](https://cloud.githubusercontent.com/assets/5156986/16885984/6f9221e2-4a9f-11e6-9aa8-fd3b29f71854.png)

**Comment by simonv3** [comment]
Over the past month or so I _have_ noticed that loading new pages on the website is incredibly slow. I wonder if it's a timeout?

**Comment by simonv3** [comment]
Do you have the same issue on staging? http://staging.openfarm.cc

**Comment by cailenfisher** [comment]
Time out would make sense, it always lags for a long time before I get that error. Still so odd that it's not logging it though. 

Staging doesn't seem to have this problem - my account doesn't exist on that DB so I will try logging out and testing production as a guest to see if that makes a difference, but at first glance I can click through several pages on staging and no delay and no errors.

**Comment by cailenfisher** [comment]
Ahhh very interesting. Maybe it is related to session despite me logging out and back in. I used an Incognito window to make sure there was no lingering session and sure enough the production site works! Still a little slow on some page loads but I was able to open several guides with no error.


![screenshot from 2016-07-15 16-14-10](https://cloud.githubusercontent.com/assets/5156986/16887466/48adfb9c-4aa8-11e6-8807-0791546660fd.png)
![screenshot from 2016-07-15 16-15-28](https://cloud.githubusercontent.com/assets/5156986/16887465/48a9bcee-4aa8-11e6-80fb-5e7fa4b69d15.png)

**Comment by simonv3** [comment]
Extra odd. That would imply that there's something wrong with our session storage? 

A totally unscientific experiment just now for me shows the page taking much longer to load for me when I'm logged in than when I'm not. It might be time to pull up page speed diagnostics as well.

**Comment by cailenfisher** [comment]
Yeah it kinda seems session related without more info. There is definitely more lag when I'm logged in but it's not just a straight HTTP timeout between me and the server, since that would produce a browser connection error not a Heroku application error. I'm wondering if it's timing out doing something internally though... S3 access maybe, but I'm not sure why it would be worse when logged in.

What's the full stack here? I glanced at the repo and it all looked like RoR, is there a client side framework too? 

The lack of logging is troublesome since it's not just slowness, I am getting consistent Application Errors and that should definitely be logged.  One thing that could help massively for debugging is turning up the error output verbosity if that's an option so it will actually say what failed when I get that

**Comment by cailenfisher** [comment]
According to Heroku docs, it's "Logplex" thingy should be capturing every HTTP transaction there might be some clues there, can you paste the last couple pages of that here?

**Comment by cailenfisher** [comment]
Eww it apparently limits how much it keeps by default. Still might be something useful in recent output but if not maybe tomorrow if we're both online at the same time at some point you can tail the logs specifically when I'm logging in and getting the application error. Turning up error output would definitely help too since it should tell me what the 500 (or etc) error was produced by right in my browser

**Comment by cailenfisher** [comment]
Ah sorry I just saw your slack msg where you suggested the same thing :) Yeah, drop me a line (I'll get these notifications faster than slack currently) and I'll try to jump on and reproduce the error

**Comment by cailenfisher** [comment]
further investigation determined the Application Error was a Heroku Error H12 "Request timeout" resulting from some unknown delay in the app exceeding 30 seconds.

Next steps might be installing the Heroku rack-timeout gem to intercept delayed / hanging requests and provide better debugging output 

https://github.com/heroku/rack-timeout

https://devcenter.heroku.com/articles/request-timeout

**Comment by simonv3** [comment]
Updating the thread: we've added rack-timeout to the gemfile. Next we'll have to do another joint logging session, or it might trigger the bug for other people too.

**Comment by simonv3** [comment]
The good news is that I now get e-mails every time that a timeout happens.

First timeout:

```
app/models/guide.rb:131:in `basic_needs'
  app/models/guide.rb:147:in `compatibility_score'
  app/views/guides/_guide_results_list.html.erb:2:in `block in _app_views_guides__guide_results_list_html_erb___604028752034315242_70282555503060'
  app/models/guide_search.rb:52:in `sort'
  app/models/guide_search.rb:52:in `method_missing'
  app/views/guides/_guide_results_list.html.erb:2:in `_app_views_guides__guide_results_list_html_erb___604028752034315242_70282555503060'
  app/views/crops/show.html.erb:77:in `_app_views_crops_show_html_erb__1960018098363589367_70282557208820'
```

Which likely implies that our compatibility score calculation is taking just too long. Maybe we need to cache this?

**Comment by simonv3** [comment]
One option is to generate those results via the API, rather than on first page load, which will already be loading a bunch of things. So show the page, and then for each result fetch the compatibility score for the guide and the user.

**Comment by simonv3** [comment]
A couple of thoughts - a lot of the errors here point directly to the impressions line in those controllers. I've commented those lines out to see if the errors go down. Those lines don't appear everywhere that the errors are coming from, but hopefully it'll decrease the amount. I've also simplified some of the code, storing values rather than recalculating them all the time.

**Comment by simonv3** [comment]
Okay, a day later, I'm no longer getting the same amount of e-mails, but I'm still getting some. Not related to the impressions lines in crops & guides controllers though, so I think that solved *part* of the problem.

The rest that I'm getting are, through `crop_search#show`: 

```
  app/models/guide.rb:102:in `basic_needs'
  app/models/guide.rb:153:in `compatibility_score'
  app/controllers/crop_searches_controller.rb:33:in `block in sort_guides'
  app/models/guide_search.rb:52:in `sort_by'
  app/models/guide_search.rb:52:in `method_missing'
  app/controllers/crop_searches_controller.rb:31:in `sort_guides'
  app/controllers/crop_searches_controller.rb:22:in `search'
```

(so basic_needs is still a problem). 

in `users#show`:

```
  app/models/user.rb:64:in `user_setting'
  app/serializers/user_serializer.rb:53:in `block in <class:UserSerializer>'
  app/controllers/api/v1/base_controller.rb:33:in `serialize_model'
  app/controllers/api/v1/users_controller.rb:17:in `show'
```

and in `crop_search#search` (again):

```
  app/views/guides/_guide_result.html.erb:6:in `block in _app_views_guides__guide_result_html_erb___1347966255032018615_69811737265060'
  app/views/guides/_guide_result.html.erb:1:in `_app_views_guides__guide_result_html_erb___1347966255032018615_69811737265060'
  app/views/guides/_guide_results_list.html.erb:3:in `block in _app_views_guides__guide_results_list_html_erb___2486981282333336298_69811737425320'
  app/views/guides/_guide_results_list.html.erb:2:in `each'
  app/views/guides/_guide_results_list.html.erb:2:in `_app_views_guides__guide_results_list_html_erb___2486981282333336298_69811737425320'
  app/views/crop_searches/show.html.erb:23:in `_app_views_crop_searches_show_html_erb__2396734303556357560_69811709614920'
  app/controllers/crop_searches_controller.rb:24:in `search'
```

**Comment by simonv3** [comment]
A thing I did two days ago - and I haven't received a timeout message since - is delete all of our impressions. The impressions field on a guide or crop is not affected, we just clear up our database a little bit.

**Comment by simonv3** [comment]
I rarely get timeout errors anymore so I'm going to call this closed. Feel free to re-open it @cailenfisher if you're still experiencing something. 

Fairly sure it was the impressions thing and a better "compatibility score" calculation.
