### ISSUE TITLE
Be able to add crops to a garden directly from the user's profile page.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#772]
As recommended by @TheChirpyWitch.

**Comment by simonv3** [comment]
This looks like it works awesomely, thanks @TheChirpyWitch :)

**Comment by TheChirpyWitch** [comment]
You're welcome, @simonv3 ! I am trying to find a new issue to work on. Any suggestions? Something that uses more Ruby, maybe?

**Comment by simonv3** [comment]
How about https://github.com/openfarmcc/OpenFarm/issues/823? I've elaborated it a bit.
