### ISSUE TITLE
Rails generator generates wrong Model

### ISSUE THREAD

**Issue by kuldeepaggarwal** [openfarmcc/OpenFarm#775]
As we are using `MongoDB` as a database, you whenever we generate any  Model, it should include `include Mongoid::Document` instead of inheriting from `ActiveRecord::Base`.

```sh
$ rails g model Test
```

```rb
# Now: 

class Test < ActiveRecord::Base
end

# Actual

class Test
  include Mongoid::Document
end
```

**Comment by simonv3** [comment]
I don't know if that's an error with OpenFarm or with Mongoid not overwriting the generator.

**Comment by kuldeepaggarwal** [comment]
@simonv3: actually when we use mongoid then we have to override Rails generator config so that Rails uses correct config while generating new Model file. Config is given somewhere in mongoid docs.

**Comment by kuldeepaggarwal** [comment]
It will help `newcomers` to generate correct Model file.

**Comment by simonv3** [comment]
👍
