### ISSUE TITLE
Add pop up for images to crops page.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#781]
Clicking on the smaller issues here should pop up a modal with the images:

https://openfarm.cc/en/crops/cherry-tomatoes

Have a look at how this is done on the guides show page.

**Comment by kuldeepaggarwal** [comment]
> Clicking on the smaller issues here should pop up a modal with the images:

I think there is a typo, clicking on the smaller **images**



Isn't similar to #534 ??

**Comment by simonv3** [comment]
Yep.
