### ISSUE TITLE
Force square images in search autocomplete?

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#786]
@TanSA05 what do you think about making all images in the autocomplete square? It's kind of awkward when they're not.
![capture](https://cloud.githubusercontent.com/assets/5524043/17530962/a904ef16-5e2e-11e6-836e-d5cdaddd1726.JPG)

**Comment by TanSA05** [comment]
Yeah, just noticed. Will fix it. :)
