### ISSUE TITLE
Guide sorting based on compatibility is broken

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#787]
This search: https://openfarm.cc/en/crops/heirloom-tomatoes

Results in this sorting for me:
![capture](https://cloud.githubusercontent.com/assets/5524043/17531308/24adfca6-5e30-11e6-873f-c275d8a8ff95.JPG)

**Comment by simonv3** [comment]
Yep.

**Comment by simonv3** [comment]
I've put a temporary fix on this, but storing the compatibility scores in the DB should probably still happen. That's in an other issue though.
