### ISSUE TITLE
Top of Guide crop image very high resolution on small screens

### ISSUE THREAD

**Issue by gabrielburnworth** [openfarmcc/OpenFarm#791]
On a guide, such as [this one for tomatoes](https://openfarm.cc/en/guides/simonv3-s-tomato):

The crop image is scaled down (in this case 500 x 375) when viewed on large screens.
![large_screen_tomato](https://cloud.githubusercontent.com/assets/12681652/17718292/e10f2fb8-63c7-11e6-82cb-4fd5e93cdbe2.png)

However, on small screens, the crop image becomes full resolution (in this case 4000 x 3000) which takes a long time to load.
![small_screen_tomato](https://cloud.githubusercontent.com/assets/12681652/17718303/ed1309f6-63c7-11e6-8f67-ef9744fdd7be.png)

**Comment by simonv3** [comment]
Thanks for taking time to report the issue @gabrielburnworth. You're right, that should absolutely be decreased.

I think most of the requirements for this are already met, the small screen just needs to reference the smaller image.
