### ISSUE TITLE
Renew SSL certificate

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#792]
Our SSL cert is going to expire in 60 days (Oct 16, 2016). We can either pay $100 to renew or use [Let's Encrypt](https://letsencrypt.org/) fo' free. Thoughts? @simonv3

**Comment by simonv3** [comment]
let's encrypt!

**Comment by roryaronson** [comment]
Bump

**Comment by simonv3** [comment]
Oh thanks for reminding me.

**Comment by simonv3** [comment]
So, I just did some quick research on how to do this:

There's some back and forth here, but eventually they get to some working solution:
https://community.letsencrypt.org/t/lets-encrypt-and-heroku-solved/4272

Luckily for us there's this: https://github.com/lgromanowski/letsencrypt-plugin

Which looks like it's pretty plug-and-play.

**Comment by simonv3** [comment]
Update: I spent some time messing with the gem for this and came across some issues - mainly I don't think it works with MongoDB.

**Comment by roryaronson** [comment]
The gem doesn't work with Mongo or Let's Encrypt doesn't work?

**Comment by simonv3** [comment]
The gem. I'm waiting for some responses on the gem to clarify that. If that's the case I don't know what's next.

**Comment by simonv3** [comment]
Tracking: https://github.com/lgromanowski/letsencrypt-plugin/issues/51#issuecomment-249583345

**Comment by roryaronson** [comment]
11 days till expiration. Can we SSH into the server and install a cert using the standard lets encrypt commands?

**Comment by simonv3** [comment]
Heroku file systems are write only as far as I'm aware. @RickCarlino might know more though?

**Comment by RickCarlino** [comment]
Heroku instances don't have SSH, so that won't be an option. You're correct that you can't store files on the file system, either.

The Right Way :tm: in the [12 Factor Methodology](https://12factor.net/) would be to [store it as an ENV variable](http://stackoverflow.com/a/14552162/1064917).

Is that an option? Been a while since I've had to set SSL stuff up.

**Comment by simonv3** [comment]
This looks promising: https://github.com/pixielabs/letsencrypt-rails-heroku

It sounds like we'd have to switch over to SNI, and I assume we have DNS set up properly?

**Comment by simonv3** [comment]
So an update: that gem says it completed properly, but I think we need to switch the app to Heroku's SNI SSL (rather than the SSL Endpoint), and @roryaronson needs to do that (as app owner). 

Right now the certificates still point to Comodo.

**Comment by roryaronson** [comment]
Alright, SSL endpoint removed, SNI enabled (by default by Heroku), and the DNS is updated. Loaded up the site and its using the certificate from Let's Encrypt! Thanks @simonv3 :)

**Comment by simonv3** [comment]
Thanks for checking and doing all that Rory! 

Going to re-open this because the Let's Encrypt certificate is only valid 90 days. There is a little scheduler task we can run to automatically renew it. But we still have to set that up.

**Comment by simonv3** [comment]
This is done!
