### ISSUE TITLE
Create/edit crop UI does not prevent invalid form data submission

### ISSUE THREAD

**Issue by CloCkWeRX** [openfarmcc/OpenFarm#806]
1. Create new crop
2. Enter a spacing of '25-50' cm (which is invalid)
3. Submit form

Expected:
I should have been prevented from entering invalid data or submitting the form

Actual:
Silently discarded invalid data, form submitted

The UI is applying classes to indicate the field is invalid; but it isn't styled.

![image](https://cloud.githubusercontent.com/assets/365751/18512621/2b14a260-7ac9-11e6-85a6-155790696c61.png)

**Comment by CloCkWeRX** [comment]
http://stackoverflow.com/questions/15300067/disable-submit-button-when-form-invalid-with-angularjs

**Comment by speizerj** [comment]
Some simple client side validation should do the trick here - I can take a look

**Comment by simonv3** [comment]
Awesome, thanks @speizerj!

**Comment by simonv3** [comment]
Let me know if you need any help with setup etc :)
