### ISSUE TITLE
'Create your own' link should prepopulate crop

### ISSUE THREAD

**Issue by CloCkWeRX** [openfarmcc/OpenFarm#807]
https://openfarm.cc/crops/57d9468f3ebce20003000079/
- Click 'Create your own' link to make a new guide

![image](https://cloud.githubusercontent.com/assets/365751/18512791/e955e388-7ac9-11e6-9b28-2bdb6b4b720c.png)

Expected:
Rosemary should be pre-chosen, given I already located the crop I want to make a guide

Actual:
![image](https://cloud.githubusercontent.com/assets/365751/18512854/1e2bb880-7aca-11e6-826b-72c190eea992.png)

**Comment by simonv3** [comment]
This would make sense to do in the URL. Add a variable `?crop=<crop-id-or-slug>` to the URL and then read that on the create guide front-end.

**Comment by TanSA05** [comment]
Mind if I take this on?
Also, I googled a bit, does the id/name have to be in the URL? I think it's possible to do it without.

**Comment by simonv3** [comment]
@TanSA05 I think linking to the right ID in the URL is probably the easiest way of doing this, but I'd love to hear what you have in mind.

**Comment by TanSA05** [comment]
Hey, @simonv3 Could you guide me a bit as to how I should go about adding the `crop name` from the `crop#show` page to the `guides#new` page?

**Comment by simonv3** [comment]
The URL ;)
