### ISSUE TITLE
Share guide button

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#818]
Make an easy way to share a guide on social platforms.

Thoughts @roryaronson?

**Comment by roryaronson** [comment]
I like this idea. I can imagine button(s) going either next to the "Favorite" button or underneath the compatibility score. We could do just one "Share" button that brings up a modal or dropdown with different options (Facebook, Twitter, Email, Tumblr, etc) or we could have different/individual buttons for each option. While individual buttons would be faster and perhaps increase engagement, I think they look ugly and crowd the interface. Thoughts?

![capture](https://cloud.githubusercontent.com/assets/5524043/18650580/a6fa758a-7e7a-11e6-9c7d-a9054386591e.JPG)

**Comment by simonv3** [comment]
I agree with using one button with a dropdown.

**Comment by sophiakc** [comment]
Can we implement a fake button and see if people clicks before implementing the whole thing?
+ I don't see this as a priority in the user journey... as people really willing to share something will copy paste the page url for now

**Comment by simonv3** [comment]
Right, but it's irked me (which is why I opened the ticket) that I had to do that. [Dogfood](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)! 

Would you pop up something like "We haven't implemented this feature yet, check out the ticket on GitHub to help us implement it"?

**Comment by CloCkWeRX** [comment]
It's probably just easiest to whack the implementation in:
https://github.com/720kb/angular-socialshare

One other thing you might want to look at is OpenGraph for the crop and guide pages.

Crops look like:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopenfarm.cc%2Fen%2Fcrops%2Fleek

Guides look like:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopenfarm.cc%2Fen%2Fguides%2Fgrowing-leek-in-trenches

Also, that tool says: https://openfarm.cc/en  - 814 likes, shares and comments, indicating some kind of sharing is happening.

**Comment by simonv3** [comment]
(I can't see either of those pages because I don't have a Facebook account, someone else will have to lead that)

angular-socialshare looks good! I'm for plug & play things.

**Comment by simonv3** [comment]
This is done!
