### ISSUE TITLE
created at and updated at dates for our models :/

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#821]

**Comment by nicholasedwards** [comment]
@simonv3, I'll get on this. Do you intend for the dates to just exist in the database, or would you also want some of them shown on the front-end?

**Comment by simonv3** [comment]
@nicholasedwards for now just the database would be great. I can't recall if ruby on rails automatically does this with mongoid?

**Comment by nicholasedwards** [comment]
My understanding is that if `Mongoid::Timestamps` is included in the model, then fields for `:created_at` and `:updated_at` will automatically be filled when the model is created or updated. For example, the source code that fills the `:created_at` field is here... https://github.com/mongoid/mongoid/blob/master/lib/mongoid/timestamps/created.rb

So, if the model includes `Mongoid::Timestamps`, we can call `instance.created_at` on any model instance, which returns a utc timestamp that was made by Ruby `Time.now.utc` when the instance was created. Same idea for `instance.updated_at`

**Comment by simonv3** [comment]
Great. Honestly I think it's probably a good idea to have this information for all of our models? Can you think of any downsides to that @nicholasedwards?

**Comment by nicholasedwards** [comment]
I don't see any pertinent downsides in terms of performance, code bloat, anything. A definite upside would be a better ability to trace database transactions for debugging purposes. Let's do it! I'll go ahead and do this for every model.

**Comment by simonv3** [comment]
Thanks @nicholasedwards!
