### ISSUE TITLE
Edit, delete icons for guides on profile page could use tooltips or other text hints

### ISSUE THREAD

**Issue by CloCkWeRX** [openfarmcc/OpenFarm#831]
On the profile view, the edit and delete controls are icons. While these make sense from experience, less skilled users may not be able to identify them well.

![screenshot from 2016-10-03 14-35-24](https://cloud.githubusercontent.com/assets/365751/19027437/00504c42-8978-11e6-84c4-1e319ea09bf8.png)

The 'edit garden' control below is a lot more user friendly:

![image](https://cloud.githubusercontent.com/assets/365751/19027477/6aaedb3a-8978-11e6-9fdc-594361ea9598.png)

**Comment by AustinLMayes** [comment]
Mind if I tackle this?

**Comment by simonv3** [comment]
Hey @AustinLMayes, thanks for offering, but there's already a PR by @speizerj for this in the works: https://github.com/openfarmcc/OpenFarm/pull/832

**Comment by TanSA05** [comment]
@simonv3 Think this should be closed? #832 resolved it.

**Comment by simonv3** [comment]
@TanSA05 Feel free to close issues when you come across something you think should be closed!

**Comment by TanSA05** [comment]
Okay.
