### ISSUE TITLE
Add survey to the front page

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#835]
We should add the survey made by @sophiakc to our front page as described in the mock-up she made. 

Survey:
https://sophiakc.typeform.com/to/VPRAoz

https://www.dropbox.com/s/vmy2ka968xwg54p/Screenshot%202016-10-04%2006.29.05.png?dl=0

**Comment by speizerj** [comment]
I can take a crack at this. It's hard to tell from the mockup - does that button have an icon/graphic that should be used?

**Comment by simonv3** [comment]
It does. It's not a must if you don't get before you start implementing, but I'll ping @sophiakc to see if she can share it here.

**Comment by simonv3** [comment]
Here it is: ![gardenerwhite](https://cloud.githubusercontent.com/assets/485583/19131375/aaac99f0-8afb-11e6-879c-fd82048c1ffd.png) (https://cloud.githubusercontent.com/assets/485583/19131375/aaac99f0-8afb-11e6-879c-fd82048c1ffd.png)

And here is a small one: ![gardenerwhitex24](https://cloud.githubusercontent.com/assets/485583/19131404/c7e6031c-8afb-11e6-9842-73684bf71f20.png) (https://cloud.githubusercontent.com/assets/485583/19131404/c7e6031c-8afb-11e6-9842-73684bf71f20.png)

(They're really there, they're just white...)
