### ISSUE TITLE
Deal with vagrant triggers.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#836]
As reported by a couple of people, either we have to give instructions on installing vagrant triggers or we have to remove it from vagrant.

**Comment by speizerj** [comment]
All I had to do was run `vagrant plugin install vagrant-triggers` - perhaps just add that to the readme?

**Comment by simonv3** [comment]
I wish there was a way for vagrant to automatically detect that it needs plugins and to have those installed on startup.

**Comment by TanSA05** [comment]
Can we remove vagrant altogether? In my experience of contributing to OpenFarm (not much), or getting others started with OpenFarm, the "Hard Way" turns out to be the easi-er way.

**Comment by simonv3** [comment]
@TanSA05 it's just not been set up 100% right because it's not been set up by a dev ops person who knows all the ins and outs. Example: Vagrant makes it possible for someone with a windows environment to hack on openfarm without much difficulty. 

There's also a lot of people who do use vagrant for dev on openfarm - you only hear about the ones who have a hard time getting it running ;). When we weren't using vagrant we had a lot of issues with people who weren't using the same system or having issues installing elasticsearch, or etc. The amount of complaints about getting started up has definitely gone down IMO. 

You should open a ticket with those issues you're experiencing so that we can iron them out! If we don't hear about them, or they just get mentioned in Slack then I'll forget about them.

**Comment by TanSA05** [comment]
Oh, okay. (Like I said, my experience - not much :P )
But, I will open a ticket for the issues with Vagrant.

**Comment by kuldeepaggarwal** [comment]
@simonv3 Then Docker can be another candidate, as I was using docker for setting and running the project only to help @tanSA05. Wdyt?

**Comment by simonv3** [comment]
@kuldeepaggarwal someone's already set up stuff to get it running, but I know even less about docker than I know about vagrant. If anyone wants to update the docker stuff so that it works (I don't even know if it works) and write instructions for how to run it, I'd be totally game for that.

**Comment by JoeHo2710** [comment]
An error:
Vagrant has detected the `vagrant-triggers` plugin. This plugin conflicts
with the internal triggers implementation. Please uninstall the `vagrant-triggers`
plugin and run the command again if you wish to use the core trigger feature. To
uninstall the plugin, run the command shown below:

  vagrant plugin uninstall vagrant-triggers

Note that the community plugin `vagrant-triggers` and the core trigger feature
in Vagrant do not have compatible syntax.

**Comment by JoeHo2710** [comment]
Looking for help, how to deal with this error:
Vagrant has detected the vagrant-triggers plugin. This plugin conflicts
with the internal triggers implementation. Please uninstall the vagrant-triggers
plugin and run the command again if you wish to use the core trigger feature. To
uninstall the plugin, run the command shown below:

vagrant plugin uninstall vagrant-triggers

Note that the community plugin vagrant-triggers and the core trigger feature
in Vagrant do not have compatible syntax.
