### ISSUE TITLE
New crop form gets 'stuck' after invalid data submission

### ISSUE THREAD

**Issue by CloCkWeRX** [openfarmcc/OpenFarm#843]
![image](https://cloud.githubusercontent.com/assets/365751/19101243/03d49840-8b0e-11e6-8eb3-46805f93ec6a.png)

 1. Create new crop
 2. Add no details
 3. Save

Backend validations kick in (good); the UI passes the message on to the user (good); but the form ends up in an uncertain state (saving)

It would be better if:
 * The form handled HTTP 422 errors and reset to an unsaved state
 * The form used required fields; disabled save button to prevent a save that can't ever work

**Comment by CloCkWeRX** [comment]
Ignore me, it's too early for me to open tickets

**Comment by simonv3** [comment]
I'm not sure those two are related actually. #806 would prevent invalid data from being entered, but in case there is a server error we should still handle that gracefully, no?

**Comment by CloCkWeRX** [comment]
Probably, but its a lot less likely to occur if its not a HTTP 422 bad request response - you'd expect a user to tolerate hitting refresh in the face of downtime.
