### ISSUE TITLE
Show that your guide is still a draft

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#849]
In the list of guides on My Profile I see a bunch of guides, but now that we have draft functionality it's not clear which ones of those are drafts:

![screenshot 2016-10-09 10 04 58](https://cloud.githubusercontent.com/assets/485583/19222560/e2a4c166-8e07-11e6-866b-c3d007b6f483.png)

Expected:

See which guides are drafts.

How I would implement this:

1. Decide - design-wise - how I would indicate that something is a draft.
2. In the .html.erb I would use the `.draft` indicator on a guide to differentiate that.
3. Do a PR. 
4. Enjoy a beverage of choice.

**Comment by roryaronson** [comment]
Possible design directions:

- Inject [DRAFT] into the displayed Guide title
- Put a sub-heading below the title that says "This Guide is a draft" followed by a "Publish Now" link
- Make another section or drop-down section titled "My Draft Guides"

**Comment by simonv3** [comment]
Would "publish now" take them to the guide for the user to publish it (the idea being that they can review it that way?), or would it publish the guide?

I like the first option.

It might be nice to show guides and draft guides separately if there are over a certain amount of guides?

**Comment by roryaronson** [comment]
I could see "publish now" doing either. It would probably be better to take the user to the guide for review and then they can use the big banner button. I think that would fall more inline with the user's expectations.

We could do a combination of the options I suggested. Like [DRAFT] with the sub-link to "Publish Now".

Drafts could always be at the top or the bottom of the list?

**Comment by jomarquez** [comment]
i am taking a stab at this. submitting a PR that adds a label after the title if guide is a draft.
![screen shot 2016-10-28 at 3 29 08 pm](https://cloud.githubusercontent.com/assets/877538/19819723/f3b60aca-9d23-11e6-9ced-b9c0a64ba246.png)

**Comment by simonv3** [comment]
👍  thanks, that would be great!
