### ISSUE TITLE
Sometimes RVM needs to be forced to use port:80 to work

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#850]
From talking to @ignaciots on Slack:

> I’m not sure why, but sometimes the gpg command fails, there is a workaround to force it to use the port 80 to get the key
> 
> like this:
> `gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys D39DC0E3`
> 
> perhaps we should include it?

We should probably include this in the wiki for installation instructions as well as just force the port in bootstrap.sh when installing RVM.

**Comment by anyangocynthia** [comment]
@simonv3 It seems that this issue was resolved in #853 could you please close it?

**Comment by simonv3** [comment]
@anyangocynthia don't you have permission to close issues?
