### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by sophiakc** [openfarmcc/OpenFarm#865]
See PR https://github.com/openfarmcc/OpenFarm/pull/864

**Comment by simonv3** [comment]
Does more need to happen on this @sophiakc ?

**Comment by sophiakc** [comment]
Someone reviewing the changes I've suggested?

**Comment by simonv3** [comment]
That ticket has been merged, so the changes should be there! I'm asking whether this ticket can be closed :)

**Comment by sophiakc** [comment]
sure!
