### ISSUE TITLE
Investigate what OpenFarm's open graph view is like: 

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#907]
From @CloCkWeRX:

> One other thing you might want to look at is OpenGraph for the crop and guide pages.
> 
> Crops look like:
> https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopenfarm.cc%2Fen%2Fcrops%2Fleek
> 
> Guides look like:
> https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopenfarm.cc%2Fen%2Fguides%2Fgrowing-leek-in-trenches
> 
> Also, that tool says: https://openfarm.cc/en - 814 likes, shares and comments, indicating some kind of sharing is happening.

Like I mentioned in that thread, I don't know what those pages look like because I don't have facebook, but if someone else wants to investigate that'd be great. 

So, what I imagine being involved here is 
1. to take a screenshot of what the opengraph views of the some of our pages are like and sharing them here
2. Make appropriate fixes to our meta data in the relevant view so that it all comes up okay.

**Comment by anyangocynthia** [comment]
@CloCkWeRX I have facebook, for now here are the screen shots of the links you posted. We are unable to start working in this due to some issues with installation. ![opengraph-for the crops](https://cloud.githubusercontent.com/assets/6637113/23301467/1aed82e2-fa9b-11e6-92d6-3bc2a0af2096.png)
![open farm](https://cloud.githubusercontent.com/assets/6637113/23301497/432c30a0-fa9b-11e6-88b5-1d25c1550c24.png)

**Comment by May-8** [comment]
I would like to work on this issue. Can someone assign me on it?

**Comment by anyangocynthia** [comment]
Found the solution to this will be doing a PR soon, just battling some installation issues. 
@May-8 feel free to pick any other issue :)

**Comment by simonv3** [comment]
Hey @anyangocynthia, how's this going?

**Comment by anyangocynthia** [comment]
@simonv3 I thought I fixed it

**Comment by simonv3** [comment]
@anyangocynthia :thumbsup: I can't check because I don't have facebook. If it's fixed let me know and I'll close this issue :)

**Comment by anyangocynthia** [comment]
@simonv3 I will recheck and get back to you

**Comment by anyangocynthia** [comment]
@simonv3 I have investigated again. The meta data is correct.The problem may occur with the Facebook scrapper failing to scrape correctly but otherwise this is fixed.

**Comment by simonv3** [comment]
Thanks @anyangocynthia!
