### ISSUE TITLE
Crop image display and management is a little broken

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#919]
Additional crop images are not being displayed on the crop view page:
<img width="741" alt="screen shot 2017-03-10 at 12 58 01 pm" src="https://cloud.githubusercontent.com/assets/5524043/23812951/7257e256-0591-11e7-8933-e1030d7b0749.png">

When you go to edit the page, none of the images attached to the crop are shown in the image manager. Pressing save will remove all images from the crop :(
<img width="507" alt="screen shot 2017-03-10 at 12 58 12 pm" src="https://cloud.githubusercontent.com/assets/5524043/23812993/a2b51482-0591-11e7-9d8a-e81ff5fc3a8b.png">

Also, fyi: I noticed this issue before I deployed the icons stuff, so the icons addition might not be what's causing the problem

**Comment by roryaronson** [comment]
I'm gonna mark this as high priority because if someone edits a crop with images, they will accidentally delete that content.

**Comment by simonv3** [comment]
:tada:
