### ISSUE TITLE
What is rubocup?

### ISSUE THREAD

**Issue by Br3nda** [openfarmcc/OpenFarm#920]
I couldn't find the answer for this... there's no rubocop.yml in this project. but there is a "config/.rubocup.yml"

is this a typo? Is it a standard for a different tool? Rubocop is in the bundle, but ... it generates pages of failures.

**Comment by simonv3** [comment]
Looks like a typo to me!

**Comment by Br3nda** [comment]
I can send a pr, that can help the project get to codestyle adherence. We're bound to find some bugs in the process.

**Comment by Br3nda** [comment]
added in #921
