### ISSUE TITLE
Update/ Replace Openfarm logo + favicon

### ISSUE THREAD

**Issue by sophiakc** [openfarmcc/OpenFarm#923]
As discussed with @roryaronson and @simonv3 , the OSI version of the logo is no longer valid. And I have eventually updated the Openfarm logo+mark assets ([see and download asset folder](https://drive.google.com/open?id=0B4a1xw3OY2hBcUdoQXVFLXM1bms))

Where does this need to be updated:
* [ ] On the homepage, top left corner: [white version of the logo (transparent background)](https://drive.google.com/open?id=0B4a1xw3OY2hBZGgySEZzNmUzazA) 
![openfarm f logo - green 219653](https://cloud.githubusercontent.com/assets/3863675/24127217/457238a2-0d90-11e7-8bb0-31f856152670.png)

* [ ] The favicon: [green # 339933 version of the mark (transparent background)](https://drive.google.com/open?id=0B4a1xw3OY2hBOEFuZTlXWkpHd2M) 
![openfarm f mark - green 219653](https://cloud.githubusercontent.com/assets/3863675/24127226/51e67328-0d90-11e7-9ff3-d0ad53c05fcb.png)

**Comment by simonv3** [comment]
Awesome, thanks @sophiakc!

**Comment by simonv3** [comment]
The svgs for this are in the google drive folder: https://drive.google.com/drive/folders/0B4a1xw3OY2hBcUdoQXVFLXM1bms
