### ISSUE TITLE
Use generic crop icon when specific crop icon does not exist

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#926]
@simonv3 has started to display the crop icons across the frontend. See the first peek under "Companion Plants" for [Kale](https://openfarm.cc/en/crops/kale)! 

<img width="421" alt="screen shot 2017-04-24 at 4 07 59 pm" src="https://cloud.githubusercontent.com/assets/5524043/25362356/3bf26570-2908-11e7-8eb0-67682ad73ff5.png">

But its pretty ugly when there is no icon available:
<img width="79" alt="screen shot 2017-04-24 at 4 09 37 pm" src="https://cloud.githubusercontent.com/assets/5524043/25362381/70b0e2c8-2908-11e7-9ba0-29cce0b54c48.png">

So we can use [this generic crop icon](https://drive.google.com/file/d/0Bzm0yyP7JMLicmZIM3cycWFlQ0E/view?usp=sharing) whenever this is the case.
<img width="180" alt="screen shot 2017-04-24 at 4 12 32 pm" src="https://cloud.githubusercontent.com/assets/5524043/25362461/d8bf1556-2908-11e7-8c24-eb848220d49a.png">

**Comment by jeffcore** [comment]
I am getting started in the open source community and would like to help out on this issue.

**Comment by simonv3** [comment]
Awesome @jeffcore! Let me know here or on [slack](http://slack.openfarm.cc/) if you need a hand.

**Comment by jeffcore** [comment]
Do you want me to store the generic-plant.svg in the public/img folder?

**Comment by simonv3** [comment]
@jeffcore Yeah, that seems like a sensible place.
