### ISSUE TITLE
Databse Content

### ISSUE THREAD

**Issue by nicmel** [openfarmcc/OpenFarm#976]
When making a standalone install, the database is nearly Empty
It would be helpfull to be able to get a Databse Dump

**Comment by RickCarlino** [comment]
@nicmel 

If your goal is to get a development environment set up, you may want to give `rails db:seed` a look. This will get your database seeded with placeholder data that will allow the UI to render properly.

If your goal is to create an offline copy of `openfarm.cc`, we do not provide that sort of thing yet.
