### ISSUE TITLE
Turn on dependabot 

### ISSUE THREAD

**Issue by Br3nda** [openfarmcc/OpenFarm#984]
Dependabot can send all security patches as a pr, so this repo doesn't fall out of date again.

**Comment by Br3nda** [comment]
dependabot.com

**Comment by RickCarlino** [comment]
@Br3nda Sounds good :+1: I have a pretty hefty branch on my local that I've been working on as time allows (usually on Fridays). I will see about getting Dependabot in with the other changes.

**Comment by Br3nda** [comment]
I'm keen to review, if you want to send canonical features from your branch as PRs.

**Comment by Br3nda** [comment]
@RickCarlino *nudge*

**Comment by Br3nda** [comment]
@RickCarlino If you give me some maintainer rights, i can do some security patching going forward

**Comment by RickCarlino** [comment]
@Br3nda It's done :heavy_check_mark: . Thanks for the help.
